create table if not exists public.auction_listings (
  id bigint generated by default as identity primary key,
  deck_id bigint not null references public.decks(id) on delete cascade,
  seller_user_id uuid not null references auth.users(id) on delete cascade,
  status text not null default 'active',
  auction_type text not null default 'reserve',
  settlement_mode text not null default 'managed',
  starting_bid_usd numeric not null default 1,
  reserve_price_usd numeric,
  current_bid_usd numeric not null default 0,
  current_high_bidder_user_id uuid references auth.users(id) on delete set null,
  reserve_met boolean not null default false,
  min_increment_usd numeric not null default 5,
  bid_count integer not null default 0,
  extension_count integer not null default 0,
  duration_days integer not null default 7,
  starts_at timestamptz not null default now(),
  ends_at timestamptz not null,
  winner_user_id uuid references auth.users(id) on delete set null,
  final_bid_usd numeric,
  manual_reviewed_at timestamptz,
  winner_acknowledged_at timestamptz,
  seller_acknowledged_at timestamptz,
  payment_requested_at timestamptz,
  paid_at timestamptz,
  shipped_at timestamptz,
  delivered_at timestamptz,
  payout_released_at timestamptz,
  buyer_payment_marked_at timestamptz,
  seller_fulfillment_marked_at timestamptz,
  buyer_received_marked_at timestamptz,
  settled_at timestamptz,
  dispute_opened_at timestamptz,
  dispute_resolved_at timestamptz,
  dispute_summary text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (status in ('active', 'pending_confirmation', 'awaiting_payment', 'paid', 'shipped', 'delivered', 'payout_released', 'awaiting_settlement', 'under_arbitration', 'completed', 'cancelled', 'expired')),
  check (auction_type in ('reserve', 'no_reserve')),
  check (settlement_mode in ('managed', 'self_cleared')),
  check (duration_days in (3, 5, 7))
);

alter table public.auction_listings
  add column if not exists settlement_mode text not null default 'managed',
  add column if not exists winner_acknowledged_at timestamptz,
  add column if not exists seller_acknowledged_at timestamptz,
  add column if not exists buyer_payment_marked_at timestamptz,
  add column if not exists seller_fulfillment_marked_at timestamptz,
  add column if not exists buyer_received_marked_at timestamptz,
  add column if not exists settled_at timestamptz,
  add column if not exists dispute_opened_at timestamptz,
  add column if not exists dispute_resolved_at timestamptz,
  add column if not exists dispute_summary text;

alter table public.auction_listings
  drop constraint if exists auction_listings_status_check;

alter table public.auction_listings
  add constraint auction_listings_status_check
  check (status in ('active', 'pending_confirmation', 'awaiting_payment', 'paid', 'shipped', 'delivered', 'payout_released', 'awaiting_settlement', 'under_arbitration', 'completed', 'cancelled', 'expired'));

alter table public.auction_listings
  drop constraint if exists auction_listings_settlement_mode_check;

alter table public.auction_listings
  add constraint auction_listings_settlement_mode_check
  check (settlement_mode in ('managed', 'self_cleared'));

create unique index if not exists auction_listings_one_open_auction_per_deck_idx
  on public.auction_listings (deck_id)
  where status in ('active', 'pending_confirmation', 'awaiting_payment', 'paid', 'shipped', 'delivered', 'awaiting_settlement', 'under_arbitration');

create index if not exists auction_listings_seller_status_idx
  on public.auction_listings (seller_user_id, status, created_at desc);

create index if not exists auction_listings_status_ends_at_idx
  on public.auction_listings (status, ends_at asc);

create table if not exists public.auction_bids (
  id bigint generated by default as identity primary key,
  auction_id bigint not null references public.auction_listings(id) on delete cascade,
  bidder_user_id uuid not null references auth.users(id) on delete cascade,
  amount_usd numeric not null,
  created_at timestamptz not null default now()
);

create index if not exists auction_bids_listing_created_at_idx
  on public.auction_bids (auction_id, created_at desc);

create index if not exists auction_bids_bidder_created_at_idx
  on public.auction_bids (bidder_user_id, created_at desc);

create table if not exists public.auction_events (
  id bigint generated by default as identity primary key,
  auction_id bigint not null references public.auction_listings(id) on delete cascade,
  actor_user_id uuid references auth.users(id) on delete set null,
  event_type text not null,
  event_data jsonb,
  created_at timestamptz not null default now()
);

create index if not exists auction_events_listing_created_at_idx
  on public.auction_events (auction_id, created_at desc);

create table if not exists public.auction_arbitration_cases (
  id bigint generated by default as identity primary key,
  auction_id bigint not null references public.auction_listings(id) on delete cascade,
  requested_by_user_id uuid not null references auth.users(id) on delete cascade,
  counterparty_user_id uuid references auth.users(id) on delete set null,
  status text not null default 'open',
  issue_type text not null,
  requested_action text,
  claimant_statement text not null,
  respondent_statement text,
  evidence_summary text,
  internal_notes text,
  outcome text,
  last_checkpoint text,
  resolution_deadline_at timestamptz,
  resolved_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (status in ('open', 'in_review', 'resolved', 'closed')),
  check (issue_type in ('non_payment', 'non_delivery', 'item_not_as_described', 'damaged', 'communication_breakdown', 'other'))
);

create index if not exists auction_arbitration_cases_auction_created_at_idx
  on public.auction_arbitration_cases (auction_id, created_at desc);

create index if not exists auction_arbitration_cases_status_created_at_idx
  on public.auction_arbitration_cases (status, created_at desc);

alter table public.auction_listings enable row level security;
alter table public.auction_bids enable row level security;
alter table public.auction_events enable row level security;
alter table public.auction_arbitration_cases enable row level security;

drop policy if exists "auction listings are publicly readable"
  on public.auction_listings;

create policy "auction listings are publicly readable"
  on public.auction_listings
  for select
  using (true);

drop policy if exists "sellers create their own auction listings"
  on public.auction_listings;

create policy "sellers create their own auction listings"
  on public.auction_listings
  for insert
  with check (seller_user_id = auth.uid());

drop policy if exists "auction listings update by participants and admin"
  on public.auction_listings;

create policy "auction listings update by participants and admin"
  on public.auction_listings
  for update
  using (
    seller_user_id = auth.uid()
    or (status = 'active' and auth.uid() is not null and seller_user_id <> auth.uid())
    or auth.jwt() ->> 'email' = 'tim.felsky@gmail.com'
  )
  with check (
    seller_user_id = auth.uid()
    or (status = 'active' and auth.uid() is not null and seller_user_id <> auth.uid())
    or auth.jwt() ->> 'email' = 'tim.felsky@gmail.com'
  );

drop policy if exists "auction bids are publicly readable"
  on public.auction_bids;

create policy "auction bids are publicly readable"
  on public.auction_bids
  for select
  using (true);

drop policy if exists "authenticated users can place bids"
  on public.auction_bids;

create policy "authenticated users can place bids"
  on public.auction_bids
  for insert
  with check (bidder_user_id = auth.uid());

drop policy if exists "auction events are readable by participants and admin"
  on public.auction_events;

create policy "auction events are readable by participants and admin"
  on public.auction_events
  for select
  using (
    exists (
      select 1
      from public.auction_listings listing
      where listing.id = auction_id
        and (
          listing.seller_user_id = auth.uid()
          or listing.current_high_bidder_user_id = auth.uid()
          or listing.winner_user_id = auth.uid()
          or auth.jwt() ->> 'email' = 'tim.felsky@gmail.com'
        )
    )
  );

drop policy if exists "auction participants and admin insert events"
  on public.auction_events;

create policy "auction participants and admin insert events"
  on public.auction_events
  for insert
  with check (
    exists (
      select 1
      from public.auction_listings listing
      where listing.id = auction_id
        and (
          listing.seller_user_id = auth.uid()
          or listing.current_high_bidder_user_id = auth.uid()
          or listing.winner_user_id = auth.uid()
          or auth.jwt() ->> 'email' = 'tim.felsky@gmail.com'
        )
    )
  );

drop policy if exists "auction arbitration cases readable by participants and admin"
  on public.auction_arbitration_cases;

create policy "auction arbitration cases readable by participants and admin"
  on public.auction_arbitration_cases
  for select
  using (
    exists (
      select 1
      from public.auction_listings listing
      where listing.id = auction_id
        and (
          listing.seller_user_id = auth.uid()
          or listing.current_high_bidder_user_id = auth.uid()
          or listing.winner_user_id = auth.uid()
          or auth.jwt() ->> 'email' = 'tim.felsky@gmail.com'
        )
    )
  );

drop policy if exists "auction arbitration cases inserted by participants and admin"
  on public.auction_arbitration_cases;

create policy "auction arbitration cases inserted by participants and admin"
  on public.auction_arbitration_cases
  for insert
  with check (
    requested_by_user_id = auth.uid()
    and exists (
      select 1
      from public.auction_listings listing
      where listing.id = auction_id
        and (
          listing.seller_user_id = auth.uid()
          or listing.current_high_bidder_user_id = auth.uid()
          or listing.winner_user_id = auth.uid()
          or auth.jwt() ->> 'email' = 'tim.felsky@gmail.com'
        )
    )
  );

drop policy if exists "auction arbitration cases updated by admin"
  on public.auction_arbitration_cases;

create policy "auction arbitration cases updated by admin"
  on public.auction_arbitration_cases
  for update
  using (auth.jwt() ->> 'email' = 'tim.felsky@gmail.com')
  with check (auth.jwt() ->> 'email' = 'tim.felsky@gmail.com');
