create table if not exists public.auction_listings (
  id bigint generated by default as identity primary key,
  deck_id bigint not null references public.decks(id) on delete cascade,
  seller_user_id uuid not null references auth.users(id) on delete cascade,
  status text not null default 'active',
  auction_type text not null default 'reserve',
  starting_bid_usd numeric not null default 1,
  reserve_price_usd numeric,
  current_bid_usd numeric not null default 0,
  current_high_bidder_user_id uuid references auth.users(id) on delete set null,
  reserve_met boolean not null default false,
  min_increment_usd numeric not null default 5,
  bid_count integer not null default 0,
  extension_count integer not null default 0,
  duration_days integer not null default 7,
  starts_at timestamptz not null default now(),
  ends_at timestamptz not null,
  winner_user_id uuid references auth.users(id) on delete set null,
  final_bid_usd numeric,
  manual_reviewed_at timestamptz,
  payment_requested_at timestamptz,
  paid_at timestamptz,
  shipped_at timestamptz,
  delivered_at timestamptz,
  payout_released_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (status in ('active', 'pending_confirmation', 'awaiting_payment', 'paid', 'shipped', 'delivered', 'payout_released', 'cancelled', 'expired')),
  check (auction_type in ('reserve', 'no_reserve')),
  check (duration_days in (3, 5, 7))
);

create unique index if not exists auction_listings_one_open_auction_per_deck_idx
  on public.auction_listings (deck_id)
  where status in ('active', 'pending_confirmation', 'awaiting_payment', 'paid', 'shipped', 'delivered');

create index if not exists auction_listings_seller_status_idx
  on public.auction_listings (seller_user_id, status, created_at desc);

create index if not exists auction_listings_status_ends_at_idx
  on public.auction_listings (status, ends_at asc);

create table if not exists public.auction_bids (
  id bigint generated by default as identity primary key,
  auction_id bigint not null references public.auction_listings(id) on delete cascade,
  bidder_user_id uuid not null references auth.users(id) on delete cascade,
  amount_usd numeric not null,
  created_at timestamptz not null default now()
);

create index if not exists auction_bids_listing_created_at_idx
  on public.auction_bids (auction_id, created_at desc);

create index if not exists auction_bids_bidder_created_at_idx
  on public.auction_bids (bidder_user_id, created_at desc);

create table if not exists public.auction_events (
  id bigint generated by default as identity primary key,
  auction_id bigint not null references public.auction_listings(id) on delete cascade,
  actor_user_id uuid references auth.users(id) on delete set null,
  event_type text not null,
  event_data jsonb,
  created_at timestamptz not null default now()
);

create index if not exists auction_events_listing_created_at_idx
  on public.auction_events (auction_id, created_at desc);

alter table public.auction_listings enable row level security;
alter table public.auction_bids enable row level security;
alter table public.auction_events enable row level security;

drop policy if exists "auction listings are publicly readable"
  on public.auction_listings;

create policy "auction listings are publicly readable"
  on public.auction_listings
  for select
  using (true);

drop policy if exists "sellers create their own auction listings"
  on public.auction_listings;

create policy "sellers create their own auction listings"
  on public.auction_listings
  for insert
  with check (seller_user_id = auth.uid());

drop policy if exists "auction listings update by participants and admin"
  on public.auction_listings;

create policy "auction listings update by participants and admin"
  on public.auction_listings
  for update
  using (
    seller_user_id = auth.uid()
    or (status = 'active' and auth.uid() is not null and seller_user_id <> auth.uid())
    or auth.jwt() ->> 'email' = 'tim.felsky@gmail.com'
  )
  with check (
    seller_user_id = auth.uid()
    or (status = 'active' and auth.uid() is not null and seller_user_id <> auth.uid())
    or auth.jwt() ->> 'email' = 'tim.felsky@gmail.com'
  );

drop policy if exists "auction bids are publicly readable"
  on public.auction_bids;

create policy "auction bids are publicly readable"
  on public.auction_bids
  for select
  using (true);

drop policy if exists "authenticated users can place bids"
  on public.auction_bids;

create policy "authenticated users can place bids"
  on public.auction_bids
  for insert
  with check (bidder_user_id = auth.uid());

drop policy if exists "auction events are readable by participants and admin"
  on public.auction_events;

create policy "auction events are readable by participants and admin"
  on public.auction_events
  for select
  using (
    exists (
      select 1
      from public.auction_listings listing
      where listing.id = auction_id
        and (
          listing.seller_user_id = auth.uid()
          or listing.current_high_bidder_user_id = auth.uid()
          or listing.winner_user_id = auth.uid()
          or auth.jwt() ->> 'email' = 'tim.felsky@gmail.com'
        )
    )
  );

drop policy if exists "auction participants and admin insert events"
  on public.auction_events;

create policy "auction participants and admin insert events"
  on public.auction_events
  for insert
  with check (
    exists (
      select 1
      from public.auction_listings listing
      where listing.id = auction_id
        and (
          listing.seller_user_id = auth.uid()
          or listing.current_high_bidder_user_id = auth.uid()
          or listing.winner_user_id = auth.uid()
          or auth.jwt() ->> 'email' = 'tim.felsky@gmail.com'
        )
    )
  );
