create table if not exists public.deck_comments (
  id bigint generated by default as identity primary key,
  deck_id bigint not null references public.decks(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  body text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists deck_comments_deck_id_created_at_idx
  on public.deck_comments (deck_id, created_at asc);

alter table public.deck_comments enable row level security;

create policy "deck comments are publicly readable"
  on public.deck_comments
  for select
  using (true);

create policy "signed in users can add deck comments"
  on public.deck_comments
  for insert
  with check (auth.uid() = user_id);

create policy "users can edit own deck comments"
  on public.deck_comments
  for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "users can delete own deck comments"
  on public.deck_comments
  for delete
  using (auth.uid() = user_id);
