alter table public.decks
  add column if not exists imported_at timestamptz default now(),
  add column if not exists format text default 'unknown';

create table if not exists public.deck_price_history (
  id bigint generated by default as identity primary key,
  deck_id bigint not null references public.decks(id) on delete cascade,
  captured_at timestamptz not null default now(),
  snapshot_type text not null default 'refresh',
  price_total_usd_foil numeric not null default 0
);

create index if not exists deck_price_history_deck_id_captured_at_idx
  on public.deck_price_history (deck_id, captured_at desc);
