create table if not exists public.deck_import_events (
  id bigint generated by default as identity primary key,
  deck_id bigint not null references public.decks(id) on delete cascade,
  actor_user_id uuid references auth.users(id) on delete set null,
  source_type text,
  event_type text not null,
  severity text not null default 'info',
  message text not null,
  details jsonb,
  created_at timestamptz not null default now(),
  check (severity in ('info', 'warning', 'error'))
);

create index if not exists deck_import_events_deck_id_created_at_idx
  on public.deck_import_events (deck_id, created_at desc);

alter table public.deck_import_events enable row level security;

create policy "deck import events are readable by deck owners and admins"
  on public.deck_import_events
  for select
  using (
    exists (
      select 1
      from public.decks
      where decks.id = deck_import_events.deck_id
        and (
          decks.user_id = auth.uid()
          or auth.jwt() ->> 'email' = 'tim.felsky@gmail.com'
        )
    )
  );

create policy "deck import events can be inserted by deck owners and admins"
  on public.deck_import_events
  for insert
  with check (
    exists (
      select 1
      from public.decks
      where decks.id = deck_import_events.deck_id
        and (
          decks.user_id = auth.uid()
          or auth.jwt() ->> 'email' = 'tim.felsky@gmail.com'
        )
    )
  );
