create table if not exists public.direct_sale_orders (
  id bigint generated by default as identity primary key,
  deck_id bigint not null references public.decks(id) on delete cascade,
  seller_user_id uuid not null references auth.users(id) on delete cascade,
  buyer_user_id uuid references auth.users(id) on delete set null,
  order_type text not null,
  status text not null default 'checkout_open',
  price_usd numeric not null default 0,
  currency text not null default 'USD',
  shipping_label_addon_usd numeric not null default 0,
  label_box_requested boolean not null default false,
  notes text,
  checkout_confirmed_at timestamptz,
  payment_confirmed_at timestamptz,
  tracking_code text,
  shipped_at timestamptz,
  delivered_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (order_type in ('buy_now', 'guaranteed_offer')),
  check (status in ('checkout_open', 'awaiting_shipment', 'shipped', 'delivered', 'completed', 'cancelled'))
);

create index if not exists direct_sale_orders_deck_idx
  on public.direct_sale_orders (deck_id, created_at desc);

create index if not exists direct_sale_orders_seller_idx
  on public.direct_sale_orders (seller_user_id, created_at desc);

create index if not exists direct_sale_orders_buyer_idx
  on public.direct_sale_orders (buyer_user_id, created_at desc);

alter table public.direct_sale_orders
  add column if not exists shipping_label_addon_usd numeric not null default 0,
  add column if not exists label_box_requested boolean not null default false,
  add column if not exists checkout_confirmed_at timestamptz,
  add column if not exists payment_confirmed_at timestamptz,
  add column if not exists tracking_code text,
  add column if not exists shipped_at timestamptz,
  add column if not exists delivered_at timestamptz;
