create table if not exists public.trade_transactions (
  id bigint generated by default as identity primary key,
  created_by uuid references auth.users(id) on delete set null,
  status text not null default 'draft',
  lane_type text not null,
  supported boolean not null default true,
  equalization_recipient text,
  equalization_amount_usd numeric not null default 0,
  platform_gross_usd numeric not null default 0,
  notes text[] not null default '{}',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.trade_transaction_participants (
  id bigint generated by default as identity primary key,
  transaction_id bigint not null references public.trade_transactions(id) on delete cascade,
  side text not null,
  user_id uuid references auth.users(id) on delete set null,
  deck_id bigint references public.decks(id) on delete set null,
  deck_value_usd numeric not null default 0,
  country_code text not null,
  shipping_usd numeric not null default 0,
  insurance_usd numeric not null default 0,
  matching_fee_usd numeric not null default 0,
  equalization_owed_usd numeric not null default 0,
  amount_due_usd numeric not null default 0,
  payment_status text not null default 'unpaid',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (transaction_id, side)
);

create table if not exists public.escrow_events (
  id bigint generated by default as identity primary key,
  transaction_id bigint not null references public.trade_transactions(id) on delete cascade,
  actor_user_id uuid references auth.users(id) on delete set null,
  event_type text not null,
  event_data jsonb,
  created_at timestamptz not null default now()
);

create index if not exists trade_transactions_created_by_idx
  on public.trade_transactions (created_by, created_at desc);

create index if not exists trade_transaction_participants_user_id_idx
  on public.trade_transaction_participants (user_id, created_at desc);

create index if not exists escrow_events_transaction_id_idx
  on public.escrow_events (transaction_id, created_at desc);

alter table public.trade_transactions enable row level security;
alter table public.trade_transaction_participants enable row level security;
alter table public.escrow_events enable row level security;

create policy "users read their own trades"
  on public.trade_transactions
  for select
  using (
    created_by = auth.uid()
    or exists (
      select 1
      from public.trade_transaction_participants p
      where p.transaction_id = id
        and p.user_id = auth.uid()
    )
    or auth.jwt() ->> 'email' = 'tim.felsky@gmail.com'
  );

create policy "users create trade drafts"
  on public.trade_transactions
  for insert
  with check (created_by = auth.uid());

create policy "trade creator and admin update trades"
  on public.trade_transactions
  for update
  using (created_by = auth.uid() or auth.jwt() ->> 'email' = 'tim.felsky@gmail.com')
  with check (created_by = auth.uid() or auth.jwt() ->> 'email' = 'tim.felsky@gmail.com');

create policy "users read participant rows for their trades"
  on public.trade_transaction_participants
  for select
  using (
    user_id = auth.uid()
    or exists (
      select 1
      from public.trade_transactions t
      where t.id = transaction_id
        and (t.created_by = auth.uid() or auth.jwt() ->> 'email' = 'tim.felsky@gmail.com')
    )
    or auth.jwt() ->> 'email' = 'tim.felsky@gmail.com'
  );

create policy "trade creator inserts participant rows"
  on public.trade_transaction_participants
  for insert
  with check (
    exists (
      select 1
      from public.trade_transactions t
      where t.id = transaction_id
        and t.created_by = auth.uid()
    )
  );

create policy "trade creator and admin update participant rows"
  on public.trade_transaction_participants
  for update
  using (
    exists (
      select 1
      from public.trade_transactions t
      where t.id = transaction_id
        and (t.created_by = auth.uid() or auth.jwt() ->> 'email' = 'tim.felsky@gmail.com')
    )
  )
  with check (
    exists (
      select 1
      from public.trade_transactions t
      where t.id = transaction_id
        and (t.created_by = auth.uid() or auth.jwt() ->> 'email' = 'tim.felsky@gmail.com')
    )
  );

create policy "users read events for their trades"
  on public.escrow_events
  for select
  using (
    exists (
      select 1
      from public.trade_transactions t
      where t.id = transaction_id
        and (
          t.created_by = auth.uid()
          or auth.jwt() ->> 'email' = 'tim.felsky@gmail.com'
          or exists (
            select 1
            from public.trade_transaction_participants p
            where p.transaction_id = t.id
              and p.user_id = auth.uid()
          )
        )
    )
  );

create policy "trade creator inserts events"
  on public.escrow_events
  for insert
  with check (
    exists (
      select 1
      from public.trade_transactions t
      where t.id = transaction_id
        and (t.created_by = auth.uid() or auth.jwt() ->> 'email' = 'tim.felsky@gmail.com')
    )
  );
