create table if not exists public.external_deck_sources (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  provider text not null,
  external_username text not null,
  profile_url text,
  status text not null default 'active',
  last_synced_at timestamptz,
  last_error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, provider, external_username),
  check (provider in ('moxfield', 'archidekt', 'deckstats', 'tappedout')),
  check (status in ('active', 'error', 'paused'))
);

create table if not exists public.external_deck_imports (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  deck_id bigint references public.decks(id) on delete set null,
  provider text not null,
  external_deck_id text not null,
  external_deck_url text,
  import_mode text not null default 'library',
  sync_status text not null default 'imported',
  external_updated_at timestamptz,
  last_error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, provider, external_deck_id),
  check (provider in ('moxfield', 'archidekt', 'deckstats', 'tappedout')),
  check (import_mode in ('library', 'manual_sync', 'import_once')),
  check (sync_status in ('imported', 'imported_with_warnings', 'error', 'skipped', 'paused'))
);

create index if not exists external_deck_sources_user_provider_idx
  on public.external_deck_sources (user_id, provider, updated_at desc);

create index if not exists external_deck_imports_user_provider_idx
  on public.external_deck_imports (user_id, provider, updated_at desc);

alter table public.external_deck_sources enable row level security;
alter table public.external_deck_imports enable row level security;

drop policy if exists "users read own external deck sources"
  on public.external_deck_sources;

create policy "users read own external deck sources"
  on public.external_deck_sources
  for select
  using (auth.uid() = user_id or auth.jwt() ->> 'email' = 'tim.felsky@gmail.com');

drop policy if exists "users manage own external deck sources"
  on public.external_deck_sources;

create policy "users manage own external deck sources"
  on public.external_deck_sources
  for all
  using (auth.uid() = user_id or auth.jwt() ->> 'email' = 'tim.felsky@gmail.com')
  with check (auth.uid() = user_id or auth.jwt() ->> 'email' = 'tim.felsky@gmail.com');

drop policy if exists "users read own external deck imports"
  on public.external_deck_imports;

create policy "users read own external deck imports"
  on public.external_deck_imports
  for select
  using (auth.uid() = user_id or auth.jwt() ->> 'email' = 'tim.felsky@gmail.com');

drop policy if exists "users manage own external deck imports"
  on public.external_deck_imports;

create policy "users manage own external deck imports"
  on public.external_deck_imports
  for all
  using (auth.uid() = user_id or auth.jwt() ->> 'email' = 'tim.felsky@gmail.com')
  with check (auth.uid() = user_id or auth.jwt() ->> 'email' = 'tim.felsky@gmail.com');
