create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  actor_user_id uuid references auth.users(id) on delete set null,
  type text not null,
  title text not null,
  body text,
  href text,
  metadata jsonb,
  read_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists notifications_user_id_read_at_created_at_idx
  on public.notifications (user_id, read_at, created_at desc);

alter table public.notifications enable row level security;

drop policy if exists "users read own notifications"
  on public.notifications;

create policy "users read own notifications"
  on public.notifications
  for select
  using (auth.uid() = user_id or auth.jwt() ->> 'email' = 'tim.felsky@gmail.com');

drop policy if exists "users update own notifications"
  on public.notifications;

create policy "users update own notifications"
  on public.notifications
  for update
  using (auth.uid() = user_id or auth.jwt() ->> 'email' = 'tim.felsky@gmail.com')
  with check (auth.uid() = user_id or auth.jwt() ->> 'email' = 'tim.felsky@gmail.com');

drop policy if exists "actors create notifications"
  on public.notifications;

create policy "actors create notifications"
  on public.notifications
  for insert
  with check (
    auth.uid() = actor_user_id
    or auth.uid() = user_id
    or auth.jwt() ->> 'email' = 'tim.felsky@gmail.com'
  );
