-- NOTE: Folded into supabase/migrations/20260622152200_reward_points.sql (run by `supabase db push`).
-- Kept for reference only — do not hand-apply.

-- Mythivex reward + engagement points foundation.
--
-- Two append-only ledgers, walled apart on purpose:
--   * reward_point_entries (MP, "hard" currency) — minted on settled money activity
--     (completed purchases, sales, ticket buys) and redeemable for checkout credit.
--     Carries a usd_basis so earns can be re-derived and audited.
--   * engagement_point_entries (SP / "Spark", soft currency) — minted on signalling
--     activity (listing, add-to-cart, profile completion, daily visits). NEVER
--     redeemable and structurally has no usd_basis. Only ever buys status/visibility.
--
-- Balances are denormalized read models maintained by triggers; the source of truth
-- is always the sum of the ledger. Mutating writes go through security-definer RPCs
-- only, mirroring create_singles_checkout. Admin override is the tim.felsky@gmail.com
-- email, consistent with the rest of the schema.

-- ---------------------------------------------------------------------------
-- Hard currency: Mythivex Points (MP)
-- ---------------------------------------------------------------------------

create table if not exists public.reward_point_entries (
  id          bigint generated by default as identity primary key,
  user_id     uuid not null references auth.users(id) on delete cascade,
  amount      integer not null,              -- +earn / -redeem (whole points)
  reason      text not null,
  source_type text,                          -- 'singles_order','direct_sale_order','event_ticket'
  source_id   text,
  usd_basis   numeric,                       -- the $ figure the earn was computed from
  metadata    jsonb not null default '{}'::jsonb,
  created_at  timestamptz not null default now(),
  constraint reward_point_entries_reason_check check (reason in (
    'singles_purchase', 'singles_sale',
    'deck_purchase', 'deck_sale',
    'ticket_purchase',
    'first_order_bonus',
    'redemption',
    'refund_adjustment', 'manual_adjustment'
  )),
  -- one earn per (user, reason, source): re-running an order-completion path can
  -- never double-mint. Redemptions/adjustments pass a unique source_id (e.g. order id).
  constraint reward_point_entries_unique_source unique (user_id, reason, source_type, source_id)
);

create index if not exists reward_point_entries_user_idx
  on public.reward_point_entries (user_id, created_at desc);

create table if not exists public.reward_point_balances (
  user_id         uuid primary key references auth.users(id) on delete cascade,
  balance         integer not null default 0,
  lifetime_earned integer not null default 0,
  updated_at      timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- Soft currency: Spark (SP)
-- ---------------------------------------------------------------------------

create table if not exists public.engagement_point_entries (
  id          bigint generated by default as identity primary key,
  user_id     uuid not null references auth.users(id) on delete cascade,
  amount      integer not null,              -- +earn / -decay (whole points), NO usd basis
  reason      text not null,
  source_type text,                          -- 'single_listing','deck_listing','cart','profile','session'
  source_id   text,
  metadata    jsonb not null default '{}'::jsonb,
  created_at  timestamptz not null default now(),
  constraint engagement_point_entries_reason_check check (reason in (
    'list_item',
    'cart_add', 'cart_add_received',
    'profile_complete',
    'daily_visit',
    'delist_reversal',
    'decay', 'manual_adjustment'
  )),
  constraint engagement_point_entries_unique_source unique (user_id, reason, source_type, source_id)
);

create index if not exists engagement_point_entries_user_idx
  on public.engagement_point_entries (user_id, created_at desc);

create index if not exists engagement_point_entries_daily_cap_idx
  on public.engagement_point_entries (user_id, reason, created_at);

create table if not exists public.engagement_point_balances (
  user_id         uuid primary key references auth.users(id) on delete cascade,
  balance         integer not null default 0,
  lifetime_earned integer not null default 0,
  season_balance  integer not null default 0,
  tier            text not null default 'newcomer',
  updated_at      timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- Tier derivation (kept in lockstep with lib/rewards/engagement.ts)
-- ---------------------------------------------------------------------------

create or replace function public.engagement_tier(p_lifetime_earned integer)
returns text
language sql
immutable
as $$
  select case
    when coalesce(p_lifetime_earned, 0) >= 5000 then 'legend'
    when coalesce(p_lifetime_earned, 0) >= 2000 then 'veteran'
    when coalesce(p_lifetime_earned, 0) >= 500  then 'trusted'
    when coalesce(p_lifetime_earned, 0) >= 100  then 'regular'
    else 'newcomer'
  end;
$$;

-- ---------------------------------------------------------------------------
-- Balance maintenance triggers
-- ---------------------------------------------------------------------------

create or replace function public.sync_reward_point_balance()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.reward_point_balances (user_id, balance, lifetime_earned, updated_at)
  values (new.user_id, new.amount, greatest(new.amount, 0), now())
  on conflict (user_id) do update
    set balance = public.reward_point_balances.balance + new.amount,
        lifetime_earned = public.reward_point_balances.lifetime_earned + greatest(new.amount, 0),
        updated_at = now();
  return new;
end;
$$;

drop trigger if exists reward_point_entries_sync_balance on public.reward_point_entries;
create trigger reward_point_entries_sync_balance
  after insert on public.reward_point_entries
  for each row execute function public.sync_reward_point_balance();

create or replace function public.sync_engagement_point_balance()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_lifetime integer;
begin
  insert into public.engagement_point_balances (user_id, balance, lifetime_earned, season_balance, tier, updated_at)
  values (
    new.user_id,
    new.amount,
    greatest(new.amount, 0),
    greatest(new.amount, 0),
    public.engagement_tier(greatest(new.amount, 0)),
    now()
  )
  on conflict (user_id) do update
    set balance = public.engagement_point_balances.balance + new.amount,
        lifetime_earned = public.engagement_point_balances.lifetime_earned + greatest(new.amount, 0),
        season_balance = greatest(0, public.engagement_point_balances.season_balance + new.amount),
        updated_at = now()
  returning lifetime_earned into v_lifetime;

  update public.engagement_point_balances
    set tier = public.engagement_tier(v_lifetime)
    where user_id = new.user_id;

  return new;
end;
$$;

drop trigger if exists engagement_point_entries_sync_balance on public.engagement_point_entries;
create trigger engagement_point_entries_sync_balance
  after insert on public.engagement_point_entries
  for each row execute function public.sync_engagement_point_balance();

-- ---------------------------------------------------------------------------
-- Row level security
-- ---------------------------------------------------------------------------

alter table public.reward_point_entries enable row level security;
alter table public.reward_point_balances enable row level security;
alter table public.engagement_point_entries enable row level security;
alter table public.engagement_point_balances enable row level security;

-- Ledgers + balances are read-own (balances are also the public-facing status surface,
-- so balances stay publicly readable for profile tiers; raw entries do not).
drop policy if exists "users read own reward entries" on public.reward_point_entries;
create policy "users read own reward entries"
  on public.reward_point_entries
  for select
  using (auth.uid() = user_id or auth.jwt() ->> 'email' = 'tim.felsky@gmail.com');

drop policy if exists "reward balances are publicly readable" on public.reward_point_balances;
create policy "reward balances are publicly readable"
  on public.reward_point_balances
  for select
  using (true);

drop policy if exists "users read own engagement entries" on public.engagement_point_entries;
create policy "users read own engagement entries"
  on public.engagement_point_entries
  for select
  using (auth.uid() = user_id or auth.jwt() ->> 'email' = 'tim.felsky@gmail.com');

drop policy if exists "engagement balances are publicly readable" on public.engagement_point_balances;
create policy "engagement balances are publicly readable"
  on public.engagement_point_balances
  for select
  using (true);

-- No insert/update policies: all writes go through the security-definer RPCs below,
-- which bypass RLS. This guarantees points can only move through audited code paths.

-- ---------------------------------------------------------------------------
-- RPCs
-- ---------------------------------------------------------------------------

-- Idempotent MP earn. Returns the number of points actually minted (0 if the
-- (user, reason, source) earn already existed). Safe to call from any
-- order-completion path.
create or replace function public.award_reward_points(
  p_user_id     uuid,
  p_amount      integer,
  p_reason      text,
  p_source_type text default null,
  p_source_id   text default null,
  p_usd_basis   numeric default null,
  p_metadata    jsonb default '{}'::jsonb
)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_inserted integer := 0;
begin
  if p_user_id is null then
    raise exception 'A user is required to award reward points.';
  end if;
  if p_amount is null or p_amount <= 0 then
    return 0;
  end if;

  insert into public.reward_point_entries (user_id, amount, reason, source_type, source_id, usd_basis, metadata)
  values (p_user_id, p_amount, p_reason, p_source_type, p_source_id, p_usd_basis, coalesce(p_metadata, '{}'::jsonb))
  on conflict (user_id, reason, source_type, source_id) do nothing;

  get diagnostics v_inserted = row_count;
  return case when v_inserted > 0 then p_amount else 0 end;
end;
$$;

-- Spend MP. Validates the live balance under a row lock and writes a negative
-- entry. Designed to be called from inside a checkout transaction (e.g.
-- create_singles_checkout) so a downstream failure rolls the redemption back.
-- Returns the points actually spent.
create or replace function public.redeem_reward_points(
  p_user_id     uuid,
  p_points      integer,
  p_source_type text,
  p_source_id   text,
  p_min_points  integer default 500
)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_balance integer := 0;
begin
  if p_user_id is null then
    raise exception 'A signed-in member is required to redeem points.';
  end if;
  if p_points is null or p_points <= 0 then
    return 0;
  end if;
  if p_points < coalesce(p_min_points, 0) then
    raise exception 'Redemptions must be at least % points.', p_min_points;
  end if;

  select balance into v_balance
  from public.reward_point_balances
  where user_id = p_user_id
  for update;

  if coalesce(v_balance, 0) < p_points then
    raise exception 'Not enough points: balance % is below requested %.', coalesce(v_balance, 0), p_points;
  end if;

  insert into public.reward_point_entries (user_id, amount, reason, source_type, source_id)
  values (p_user_id, -p_points, 'redemption', p_source_type, p_source_id);

  return p_points;
end;
$$;

-- Idempotent SP earn with an optional same-day cap per reason. Per-entity dedupe
-- comes from the unique constraint; pass a date-bucketed source_id (e.g. the
-- current date) for once-per-day signals. Returns the points actually minted.
create or replace function public.award_engagement_points(
  p_user_id          uuid,
  p_amount           integer,
  p_reason           text,
  p_source_type      text default null,
  p_source_id        text default null,
  p_daily_cap        integer default null,
  p_metadata         jsonb default '{}'::jsonb
)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_awarded_today integer := 0;
  v_grant integer;
  v_inserted integer := 0;
begin
  if p_user_id is null then
    raise exception 'A user is required to award engagement points.';
  end if;
  if p_amount is null or p_amount <= 0 then
    return 0;
  end if;

  v_grant := p_amount;

  if p_daily_cap is not null then
    select coalesce(sum(amount), 0) into v_awarded_today
    from public.engagement_point_entries
    where user_id = p_user_id
      and reason = p_reason
      and amount > 0
      and created_at >= date_trunc('day', now());

    v_grant := least(v_grant, greatest(0, p_daily_cap - v_awarded_today));
    if v_grant <= 0 then
      return 0;
    end if;
  end if;

  insert into public.engagement_point_entries (user_id, amount, reason, source_type, source_id, metadata)
  values (p_user_id, v_grant, p_reason, p_source_type, p_source_id, coalesce(p_metadata, '{}'::jsonb))
  on conflict (user_id, reason, source_type, source_id) do nothing;

  get diagnostics v_inserted = row_count;
  return case when v_inserted > 0 then v_grant else 0 end;
end;
$$;

grant execute on function public.award_reward_points(uuid, integer, text, text, text, numeric, jsonb) to authenticated;
grant execute on function public.redeem_reward_points(uuid, integer, text, text, integer) to authenticated;
grant execute on function public.award_engagement_points(uuid, integer, text, text, text, integer, jsonb) to authenticated;
