create table if not exists public.external_single_sources (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  provider text not null,
  external_account text not null,
  source_scope text not null default 'singles',
  source_key text not null,
  source_name text,
  source_url text,
  status text not null default 'active',
  imported_item_count integer not null default 0,
  last_synced_at timestamptz,
  last_error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, provider, source_scope, source_key),
  check (provider in ('moxfield', 'archidekt')),
  check (source_scope in ('singles', 'full_collection')),
  check (status in ('active', 'error', 'paused'))
);

create table if not exists public.external_single_imports (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  provider text not null,
  source_scope text not null default 'singles',
  source_key text not null,
  source_name text,
  source_url text,
  sync_status text not null default 'imported',
  imported_item_count integer not null default 0,
  warning_count integer not null default 0,
  skipped_count integer not null default 0,
  failed_count integer not null default 0,
  last_error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, provider, source_scope, source_key),
  check (provider in ('moxfield', 'archidekt')),
  check (source_scope in ('singles', 'full_collection')),
  check (sync_status in ('imported', 'imported_with_warnings', 'error', 'skipped', 'paused'))
);

create table if not exists public.single_inventory_items (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  provider text not null,
  source_scope text not null default 'singles',
  source_account text,
  source_collection_key text not null,
  source_collection_name text,
  source_collection_url text,
  source_item_key text not null,
  inventory_status text not null default 'staged',
  card_name text not null,
  quantity integer not null default 1,
  condition text not null default 'near_mint',
  condition_source text not null default 'import_default',
  language text not null default 'en',
  foil boolean not null default false,
  set_code text,
  set_name text,
  collector_number text,
  scryfall_id text,
  oracle_id text,
  artist_name text,
  released_at date,
  finishes text[] not null default '{}'::text[],
  oracle_text text,
  type_line text,
  rarity text,
  mana_cost text,
  cmc numeric,
  power text,
  toughness text,
  color_identity text[] not null default '{}'::text[],
  keywords text[] not null default '{}'::text[],
  image_url text,
  price_usd numeric,
  price_usd_foil numeric,
  price_usd_etched numeric,
  price_eur numeric,
  price_eur_foil numeric,
  price_tix numeric,
  buy_now_price_usd numeric,
  buy_now_currency text not null default 'USD',
  import_warning text,
  imported_at timestamptz not null default now(),
  last_enriched_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, provider, source_collection_key, source_item_key),
  check (provider in ('moxfield', 'archidekt')),
  check (source_scope in ('singles', 'full_collection')),
  check (inventory_status in ('staged', 'buy_it_now_live', 'checked_out', 'completed')),
  check (condition in ('damaged', 'heavy_play', 'moderate_play', 'light_play', 'near_mint')),
  check (condition_source in ('import_default', 'manual'))
);

create table if not exists public.single_import_events (
  id bigint generated by default as identity primary key,
  single_inventory_item_id bigint references public.single_inventory_items(id) on delete cascade,
  actor_user_id uuid references auth.users(id) on delete set null,
  provider text,
  source_scope text,
  event_type text not null,
  severity text not null default 'info',
  message text not null,
  details jsonb,
  created_at timestamptz not null default now(),
  check (severity in ('info', 'warning', 'error'))
);

create index if not exists external_single_sources_user_provider_idx
  on public.external_single_sources (user_id, provider, updated_at desc);

create index if not exists external_single_imports_user_provider_idx
  on public.external_single_imports (user_id, provider, updated_at desc);

create index if not exists single_inventory_items_user_status_idx
  on public.single_inventory_items (user_id, inventory_status, updated_at desc);

create index if not exists single_inventory_items_user_oracle_idx
  on public.single_inventory_items (user_id, oracle_id, card_name);

create index if not exists single_import_events_item_idx
  on public.single_import_events (single_inventory_item_id, created_at desc);

alter table public.external_single_sources enable row level security;
alter table public.external_single_imports enable row level security;
alter table public.single_inventory_items enable row level security;
alter table public.single_import_events enable row level security;

drop policy if exists "users read own external single sources"
  on public.external_single_sources;

create policy "users read own external single sources"
  on public.external_single_sources
  for select
  using (auth.uid() = user_id or auth.jwt() ->> 'email' = 'tim.felsky@gmail.com');

drop policy if exists "users manage own external single sources"
  on public.external_single_sources;

create policy "users manage own external single sources"
  on public.external_single_sources
  for all
  using (auth.uid() = user_id or auth.jwt() ->> 'email' = 'tim.felsky@gmail.com')
  with check (auth.uid() = user_id or auth.jwt() ->> 'email' = 'tim.felsky@gmail.com');

drop policy if exists "users read own external single imports"
  on public.external_single_imports;

create policy "users read own external single imports"
  on public.external_single_imports
  for select
  using (auth.uid() = user_id or auth.jwt() ->> 'email' = 'tim.felsky@gmail.com');

drop policy if exists "users manage own external single imports"
  on public.external_single_imports;

create policy "users manage own external single imports"
  on public.external_single_imports
  for all
  using (auth.uid() = user_id or auth.jwt() ->> 'email' = 'tim.felsky@gmail.com')
  with check (auth.uid() = user_id or auth.jwt() ->> 'email' = 'tim.felsky@gmail.com');

drop policy if exists "users read own single inventory items"
  on public.single_inventory_items;

create policy "users read own single inventory items"
  on public.single_inventory_items
  for select
  using (auth.uid() = user_id or auth.jwt() ->> 'email' = 'tim.felsky@gmail.com');

drop policy if exists "users manage own single inventory items"
  on public.single_inventory_items;

create policy "users manage own single inventory items"
  on public.single_inventory_items
  for all
  using (auth.uid() = user_id or auth.jwt() ->> 'email' = 'tim.felsky@gmail.com')
  with check (auth.uid() = user_id or auth.jwt() ->> 'email' = 'tim.felsky@gmail.com');

drop policy if exists "users read own single import events"
  on public.single_import_events;

create policy "users read own single import events"
  on public.single_import_events
  for select
  using (
    exists (
      select 1
      from public.single_inventory_items items
      where items.id = single_inventory_item_id
        and (items.user_id = auth.uid() or auth.jwt() ->> 'email' = 'tim.felsky@gmail.com')
    )
  );
