alter table public.single_inventory_items
  add column if not exists marketplace_visible boolean not null default false,
  add column if not exists marketplace_status text not null default 'draft',
  add column if not exists marketplace_quantity_available integer not null default 0,
  add column if not exists marketplace_price_usd numeric,
  add column if not exists marketplace_currency text not null default 'USD',
  add column if not exists marketplace_notes text;

alter table public.single_inventory_items
  drop constraint if exists single_inventory_items_marketplace_status_check;

alter table public.single_inventory_items
  add constraint single_inventory_items_marketplace_status_check
  check (marketplace_status in ('draft', 'active', 'paused', 'sold_out'));

create index if not exists single_inventory_items_public_market_idx
  on public.single_inventory_items (marketplace_visible, marketplace_status, marketplace_quantity_available, marketplace_price_usd);

drop policy if exists "public read active single marketplace items"
  on public.single_inventory_items;

create policy "public read active single marketplace items"
  on public.single_inventory_items
  for select
  using (
    (
      marketplace_visible = true
      and marketplace_status = 'active'
      and marketplace_quantity_available > 0
      and coalesce(marketplace_price_usd, 0) > 0
    )
    or auth.uid() = user_id
    or auth.jwt() ->> 'email' = 'tim.felsky@gmail.com'
  );

create table if not exists public.singles_orders (
  id bigint generated by default as identity primary key,
  buyer_user_id uuid not null references auth.users(id) on delete cascade,
  seller_user_id uuid not null references auth.users(id) on delete cascade,
  status text not null default 'awaiting_shipment',
  currency text not null default 'USD',
  item_subtotal_usd numeric not null default 0,
  discount_tier_key text not null default 'none',
  discount_tier_label text not null default 'No volume discount yet',
  discount_amount_usd numeric not null default 0,
  discounted_subtotal_usd numeric not null default 0,
  shipping_amount_usd numeric not null default 0,
  tax_amount_usd numeric not null default 0,
  grand_total_usd numeric not null default 0,
  item_count integer not null default 0,
  pricing_snapshot jsonb not null default '{}'::jsonb,
  cart_snapshot jsonb not null default '[]'::jsonb,
  notes text,
  checkout_confirmed_at timestamptz not null default now(),
  payment_confirmed_at timestamptz not null default now(),
  tracking_code text,
  shipped_at timestamptz,
  delivered_at timestamptz,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (status in ('awaiting_shipment', 'shipped', 'delivered', 'completed', 'cancelled')),
  check (discount_tier_key in ('none', 'tier_20', 'tier_25'))
);

create table if not exists public.singles_order_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.singles_orders(id) on delete cascade,
  single_inventory_item_id bigint not null references public.single_inventory_items(id) on delete restrict,
  seller_user_id uuid not null references auth.users(id) on delete cascade,
  quantity integer not null default 1,
  unit_price_usd numeric not null default 0,
  line_subtotal_usd numeric not null default 0,
  card_name text not null,
  set_name text,
  set_code text,
  collector_number text,
  foil boolean not null default false,
  condition text,
  language text,
  image_url text,
  pricing_snapshot jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (quantity > 0)
);

create index if not exists singles_orders_buyer_idx
  on public.singles_orders (buyer_user_id, created_at desc);

create index if not exists singles_orders_seller_idx
  on public.singles_orders (seller_user_id, created_at desc);

create index if not exists singles_order_items_order_idx
  on public.singles_order_items (order_id, created_at asc);

create index if not exists singles_order_items_seller_idx
  on public.singles_order_items (seller_user_id, created_at desc);

alter table public.singles_orders enable row level security;
alter table public.singles_order_items enable row level security;

drop policy if exists "buyers and sellers read singles orders"
  on public.singles_orders;

create policy "buyers and sellers read singles orders"
  on public.singles_orders
  for select
  using (
    auth.uid() = buyer_user_id
    or auth.uid() = seller_user_id
    or auth.jwt() ->> 'email' = 'tim.felsky@gmail.com'
  );

drop policy if exists "buyers insert own singles orders"
  on public.singles_orders;

create policy "buyers insert own singles orders"
  on public.singles_orders
  for insert
  with check (
    auth.uid() = buyer_user_id
    or auth.jwt() ->> 'email' = 'tim.felsky@gmail.com'
  );

drop policy if exists "buyers and sellers update singles orders"
  on public.singles_orders;

create policy "buyers and sellers update singles orders"
  on public.singles_orders
  for update
  using (
    auth.uid() = buyer_user_id
    or auth.uid() = seller_user_id
    or auth.jwt() ->> 'email' = 'tim.felsky@gmail.com'
  )
  with check (
    auth.uid() = buyer_user_id
    or auth.uid() = seller_user_id
    or auth.jwt() ->> 'email' = 'tim.felsky@gmail.com'
  );

drop policy if exists "buyers and sellers read singles order items"
  on public.singles_order_items;

create policy "buyers and sellers read singles order items"
  on public.singles_order_items
  for select
  using (
    exists (
      select 1
      from public.singles_orders orders
      where orders.id = order_id
        and (
          orders.buyer_user_id = auth.uid()
          or orders.seller_user_id = auth.uid()
          or auth.jwt() ->> 'email' = 'tim.felsky@gmail.com'
        )
    )
  );

create or replace function public.create_singles_checkout(
  p_buyer_user_id uuid,
  p_cart_items jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_item record;
  v_listing record;
  v_order_id bigint;
  v_subtotal numeric := 0;
  v_discount_amount numeric := 0;
  v_discounted_subtotal numeric := 0;
  v_shipping_amount numeric := 0;
  v_tax_amount numeric := 0;
  v_grand_total numeric := 0;
  v_discount_tier_key text := 'none';
  v_discount_tier_label text := 'No volume discount yet';
  v_seller_user_id uuid := null;
  v_item_count integer := 0;
  v_line_subtotal numeric := 0;
  v_price numeric := 0;
  v_available integer := 0;
  v_shipping_method text := 'pwe_untracked';
  v_shipping_label text := 'PWE Plain White Envelope';
  v_shipping_description text := 'No tracking. Available for up to 10 cards when the order stays at $30 or less in Canada.';
begin
  if p_buyer_user_id is null then
    raise exception 'A signed-in buyer is required.';
  end if;

  if p_cart_items is null or jsonb_typeof(p_cart_items) <> 'array' or jsonb_array_length(p_cart_items) = 0 then
    raise exception 'Your cart is empty.';
  end if;

  create temporary table temp_checkout_items (
    single_inventory_item_id bigint not null,
    quantity integer not null
  ) on commit drop;

  insert into temp_checkout_items (single_inventory_item_id, quantity)
  select
    (item ->> 'singleInventoryItemId')::bigint,
    greatest(1, floor((item ->> 'quantity')::numeric))::integer
  from jsonb_array_elements(p_cart_items) item;

  delete from temp_checkout_items
  where single_inventory_item_id is null or quantity <= 0;

  if not exists (select 1 from temp_checkout_items) then
    raise exception 'Your cart does not contain any valid items.';
  end if;

  for v_item in
    select single_inventory_item_id, sum(quantity)::integer as quantity
    from temp_checkout_items
    group by single_inventory_item_id
    order by single_inventory_item_id
  loop
    select *
    into v_listing
    from public.single_inventory_items
    where id = v_item.single_inventory_item_id
    for update;

    if not found then
      raise exception 'One of the selected singles could not be found.';
    end if;

    if v_listing.marketplace_visible is distinct from true
      or v_listing.marketplace_status <> 'active'
      or coalesce(v_listing.marketplace_price_usd, 0) <= 0
      or coalesce(v_listing.marketplace_quantity_available, 0) <= 0
      or v_listing.inventory_status <> 'buy_it_now_live'
    then
      raise exception '% is no longer available for checkout.', v_listing.card_name;
    end if;

    if v_seller_user_id is null then
      v_seller_user_id := v_listing.user_id;
    elsif v_seller_user_id <> v_listing.user_id then
      raise exception 'For now, checkout supports singles from one seller at a time.';
    end if;

    v_available := greatest(0, coalesce(v_listing.marketplace_quantity_available, 0));
    if v_available < v_item.quantity then
      raise exception '% only has % copy/copies available right now.', v_listing.card_name, v_available;
    end if;

    v_price := round(coalesce(v_listing.marketplace_price_usd, 0)::numeric, 2);
    v_line_subtotal := round(v_price * v_item.quantity, 2);
    v_subtotal := round(v_subtotal + v_line_subtotal, 2);
    v_item_count := v_item_count + v_item.quantity;
  end loop;

  if v_subtotal >= 200 then
    v_discount_tier_key := 'tier_25';
    v_discount_tier_label := '25% off orders $200+';
    v_discount_amount := round(v_subtotal * 0.25, 2);
  elsif v_subtotal >= 100 then
    v_discount_tier_key := 'tier_20';
    v_discount_tier_label := '20% off orders $100+';
    v_discount_amount := round(v_subtotal * 0.20, 2);
  else
    v_discount_amount := 0;
  end if;

  v_discounted_subtotal := round(v_subtotal - v_discount_amount, 2);
  if v_subtotal > 30 or v_item_count > 10 then
    v_shipping_method := 'tracked_padded_mailer';
    v_shipping_label := 'Padded mailer with tracking';
    v_shipping_description := 'Automatic for orders over $30 or more than 10 cards in Canada.';
    v_shipping_amount := 15;
  else
    v_shipping_method := 'pwe_untracked';
    v_shipping_label := 'PWE Plain White Envelope';
    v_shipping_description := 'No tracking. Available for up to 10 cards when the order stays at $30 or less in Canada.';
    v_shipping_amount := 5;
  end if;
  v_grand_total := round(v_discounted_subtotal + v_shipping_amount + v_tax_amount, 2);

  insert into public.singles_orders (
    buyer_user_id,
    seller_user_id,
    status,
    currency,
    item_subtotal_usd,
    discount_tier_key,
    discount_tier_label,
    discount_amount_usd,
    discounted_subtotal_usd,
    shipping_amount_usd,
    tax_amount_usd,
    grand_total_usd,
    item_count,
    pricing_snapshot,
    cart_snapshot
  )
  values (
    p_buyer_user_id,
    v_seller_user_id,
    'awaiting_shipment',
    'USD',
    v_subtotal,
    v_discount_tier_key,
    v_discount_tier_label,
    v_discount_amount,
    v_discounted_subtotal,
    v_shipping_amount,
    v_tax_amount,
    v_grand_total,
    v_item_count,
    jsonb_build_object(
      'subtotal', v_subtotal,
      'discountTier', v_discount_tier_key,
      'tierLabel', v_discount_tier_label,
      'discountAmount', v_discount_amount,
      'discountedSubtotal', v_discounted_subtotal,
      'shippingMethod', v_shipping_method,
      'shippingLabel', v_shipping_label,
      'shippingDescription', v_shipping_description,
      'shippingAmount', v_shipping_amount,
      'taxAmount', v_tax_amount,
      'grandTotal', v_grand_total
    ),
    p_cart_items
  )
  returning id into v_order_id;

  for v_item in
    select single_inventory_item_id, sum(quantity)::integer as quantity
    from temp_checkout_items
    group by single_inventory_item_id
    order by single_inventory_item_id
  loop
    select *
    into v_listing
    from public.single_inventory_items
    where id = v_item.single_inventory_item_id
    for update;

    v_price := round(coalesce(v_listing.marketplace_price_usd, 0)::numeric, 2);
    v_line_subtotal := round(v_price * v_item.quantity, 2);

    insert into public.singles_order_items (
      order_id,
      single_inventory_item_id,
      seller_user_id,
      quantity,
      unit_price_usd,
      line_subtotal_usd,
      card_name,
      set_name,
      set_code,
      collector_number,
      foil,
      condition,
      language,
      image_url,
      pricing_snapshot
    )
    values (
      v_order_id,
      v_listing.id,
      v_listing.user_id,
      v_item.quantity,
      v_price,
      v_line_subtotal,
      v_listing.card_name,
      v_listing.set_name,
      v_listing.set_code,
      v_listing.collector_number,
      coalesce(v_listing.foil, false),
      v_listing.condition,
      v_listing.language,
      v_listing.image_url,
      jsonb_build_object(
        'unitPriceUsd', v_price,
        'lineSubtotalUsd', v_line_subtotal
      )
    );

    update public.single_inventory_items
    set
      marketplace_quantity_available = marketplace_quantity_available - v_item.quantity,
      marketplace_status = case
        when marketplace_quantity_available - v_item.quantity <= 0 then 'sold_out'
        else marketplace_status
      end,
      marketplace_visible = case
        when marketplace_quantity_available - v_item.quantity <= 0 then false
        else marketplace_visible
      end,
      inventory_status = case
        when marketplace_quantity_available - v_item.quantity <= 0 then 'checked_out'
        else inventory_status
      end,
      updated_at = now()
    where id = v_listing.id;
  end loop;

  return jsonb_build_object('orderId', v_order_id);
end;
$$;

grant execute on function public.create_singles_checkout(uuid, jsonb) to authenticated;
