create table if not exists public.trade_offers (
  id bigint generated by default as identity primary key,
  offered_by_user_id uuid not null references auth.users(id) on delete cascade,
  requested_user_id uuid not null references auth.users(id) on delete cascade,
  offered_deck_id bigint not null references public.decks(id) on delete cascade,
  requested_deck_id bigint not null references public.decks(id) on delete cascade,
  cash_equalization_usd numeric not null default 0,
  status text not null default 'pending',
  message text,
  parent_offer_id bigint references public.trade_offers(id) on delete set null,
  superseded_by_offer_id bigint references public.trade_offers(id) on delete set null,
  accepted_trade_transaction_id bigint references public.trade_transactions(id) on delete set null,
  last_action_by_user_id uuid references auth.users(id) on delete set null,
  offered_by_viewed_at timestamptz,
  requested_user_viewed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (status in ('pending', 'accepted', 'declined', 'cancelled', 'countered'))
);

alter table public.trade_offers
  add column if not exists parent_offer_id bigint references public.trade_offers(id) on delete set null,
  add column if not exists superseded_by_offer_id bigint references public.trade_offers(id) on delete set null,
  add column if not exists accepted_trade_transaction_id bigint references public.trade_transactions(id) on delete set null,
  add column if not exists last_action_by_user_id uuid references auth.users(id) on delete set null,
  add column if not exists offered_by_viewed_at timestamptz,
  add column if not exists requested_user_viewed_at timestamptz;

create index if not exists trade_offers_offered_by_idx
  on public.trade_offers (offered_by_user_id, created_at desc);

create index if not exists trade_offers_requested_user_idx
  on public.trade_offers (requested_user_id, created_at desc);

create index if not exists trade_offers_requested_deck_idx
  on public.trade_offers (requested_deck_id, created_at desc);

alter table public.trade_offers enable row level security;

create policy "users read their own trade offers"
  on public.trade_offers
  for select
  using (
    offered_by_user_id = auth.uid()
    or requested_user_id = auth.uid()
    or auth.jwt() ->> 'email' = 'tim.felsky@gmail.com'
  );

create policy "users create their own trade offers"
  on public.trade_offers
  for insert
  with check (
    offered_by_user_id = auth.uid()
    and offered_by_user_id <> requested_user_id
  );

create policy "offer participants update their trade offers"
  on public.trade_offers
  for update
  using (
    offered_by_user_id = auth.uid()
    or requested_user_id = auth.uid()
    or auth.jwt() ->> 'email' = 'tim.felsky@gmail.com'
  )
  with check (
    offered_by_user_id = auth.uid()
    or requested_user_id = auth.uid()
    or auth.jwt() ->> 'email' = 'tim.felsky@gmail.com'
  );
