create table if not exists public.profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  username text unique,
  bio text,
  avatar_url text,
  location_country text,
  location_region text,
  preferred_currency text default 'USD',
  marketplace_tagline text,
  website_url text,
  instagram_url text,
  youtube_url text,
  whatnot_url text,
  ebay_url text,
  cardmarket_url text,
  tcgplayer_url text,
  can_ship_domestic boolean not null default true,
  can_ship_international boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.profile_private (
  user_id uuid primary key references auth.users(id) on delete cascade,
  legal_first_name text,
  legal_last_name text,
  support_email text,
  shipping_name text,
  shipping_address_line_1 text,
  shipping_city text,
  shipping_region text,
  shipping_postal_code text,
  shipping_country text,
  customer_service_notes text,
  government_id_storage_key text,
  marketing_opt_in_email boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.profile_verifications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  verification_type text not null,
  status text not null default 'pending',
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, verification_type)
);

create table if not exists public.profile_reputation_summary (
  user_id uuid primary key references auth.users(id) on delete cascade,
  completed_trades_count integer not null default 0,
  successful_shipments_count integer not null default 0,
  positive_feedback_count integer not null default 0,
  negative_feedback_count integer not null default 0,
  external_rating_average numeric,
  external_rating_count integer not null default 0,
  verification_badges text[] not null default '{}',
  is_manually_verified boolean not null default false,
  is_known_user boolean not null default false,
  is_friend_of_platform boolean not null default false,
  banned_status text not null default 'active',
  banned_reason text,
  manual_review_notes text,
  last_seen_at timestamptz,
  avg_trade_reply_hours numeric,
  last_login_ip_country text,
  internal_user_rating numeric,
  internal_validation_score integer,
  internal_validation_tier text,
  internal_validation_notes text[] not null default '{}',
  internal_validation_last_calculated_at timestamptz,
  updated_at timestamptz not null default now()
);

alter table public.profile_reputation_summary
  add column if not exists last_seen_at timestamptz,
  add column if not exists avg_trade_reply_hours numeric,
  add column if not exists last_login_ip_country text,
  add column if not exists internal_user_rating numeric,
  add column if not exists internal_validation_score integer,
  add column if not exists internal_validation_tier text,
  add column if not exists internal_validation_notes text[] not null default '{}',
  add column if not exists internal_validation_last_calculated_at timestamptz,
  add column if not exists approval_status text not null default 'pending',
  add column if not exists approval_notes text,
  add column if not exists approved_at timestamptz,
  add column if not exists approved_by uuid references auth.users(id) on delete set null;

alter table public.profiles enable row level security;
alter table public.profile_private enable row level security;
alter table public.profile_verifications enable row level security;
alter table public.profile_reputation_summary enable row level security;

create policy "profiles are publicly readable"
  on public.profiles
  for select
  using (true);

create policy "users manage own profile"
  on public.profiles
  for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "users read own private profile"
  on public.profile_private
  for select
  using (auth.uid() = user_id);

create policy "users manage own private profile"
  on public.profile_private
  for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "users read own verifications"
  on public.profile_verifications
  for select
  using (auth.uid() = user_id or auth.jwt() ->> 'email' = 'tim.felsky@gmail.com');

create policy "users submit own verifications"
  on public.profile_verifications
  for insert
  with check (auth.uid() = user_id);

create policy "users update own pending verifications"
  on public.profile_verifications
  for update
  using (auth.uid() = user_id or auth.jwt() ->> 'email' = 'tim.felsky@gmail.com')
  with check (auth.uid() = user_id or auth.jwt() ->> 'email' = 'tim.felsky@gmail.com');

create policy "reputation summaries are publicly readable"
  on public.profile_reputation_summary
  for select
  using (true);

create policy "users create own summary row"
  on public.profile_reputation_summary
  for insert
  with check (auth.uid() = user_id);

create policy "users update own summary row"
  on public.profile_reputation_summary
  for update
  using (auth.uid() = user_id or auth.jwt() ->> 'email' = 'tim.felsky@gmail.com')
  with check (auth.uid() = user_id or auth.jwt() ->> 'email' = 'tim.felsky@gmail.com');
