// Arb'r — sample eBay listings used when eBay API credentials aren't
// configured (or a live call fails). Mirrors the shape of real Best Offer MTG
// single listings so the engine, UI, and tests all exercise realistic data.

import type { EbayListing } from './types'

export const SAMPLE_EBAY_LISTINGS: EbayListing[] = [
  {
    id: 'sample-1',
    title: 'MTG Rhystic Study Prophecy NM Commander Staple - Best Offer!',
    askingPrice: 38,
    bestOfferEnabled: true,
    condition: 'near_mint',
    shippingCost: 0,
    quantity: 1,
    cardName: 'Rhystic Study',
    setHint: 'Prophecy',
    foil: false,
    url: 'https://www.ebay.com/itm/sample-1',
    imageUrl: null,
    seller: 'cardbarn_samples',
  },
  {
    id: 'sample-2',
    title: 'Cyclonic Rift Commander 2016 MTG Lightly Played OBO',
    askingPrice: 22,
    bestOfferEnabled: true,
    condition: 'lightly_played',
    shippingCost: 1,
    quantity: 1,
    cardName: 'Cyclonic Rift',
    setHint: 'Commander 2016',
    foil: false,
    url: 'https://www.ebay.com/itm/sample-2',
    imageUrl: null,
    seller: 'cardbarn_samples',
  },
  {
    id: 'sample-3',
    title: 'Smothering Tithe Ravnica Allegiance MTG x1 NM - or best offer',
    askingPrice: 30,
    bestOfferEnabled: true,
    condition: 'near_mint',
    shippingCost: 0,
    quantity: 1,
    cardName: 'Smothering Tithe',
    setHint: 'Ravnica Allegiance',
    foil: false,
    url: 'https://www.ebay.com/itm/sample-3',
    imageUrl: null,
    seller: 'mox_emporium',
  },
  {
    id: 'sample-4',
    title: 'FOIL Dockside Extortionist Commander Legends MTG NM',
    askingPrice: 60,
    bestOfferEnabled: true,
    condition: 'near_mint',
    shippingCost: 4,
    quantity: 1,
    cardName: 'Dockside Extortionist',
    setHint: 'Commander Legends',
    foil: true,
    url: 'https://www.ebay.com/itm/sample-4',
    imageUrl: null,
    seller: 'mox_emporium',
  },
  {
    id: 'sample-5',
    title: 'Sol Ring Commander MTG Played Bulk - Buy It Now Only',
    askingPrice: 3,
    bestOfferEnabled: false,
    condition: 'moderately_played',
    shippingCost: 1,
    quantity: 1,
    cardName: 'Sol Ring',
    setHint: 'Commander',
    foil: false,
    url: 'https://www.ebay.com/itm/sample-5',
    imageUrl: null,
    seller: 'bulk_bin_co',
  },
  {
    id: 'sample-6',
    title: 'The Great Henge Throne of Eldraine MTG NM x1 OBO accepted',
    askingPrice: 48,
    bestOfferEnabled: true,
    condition: 'near_mint',
    shippingCost: 0,
    quantity: 1,
    cardName: 'The Great Henge',
    setHint: 'Throne of Eldraine',
    foil: false,
    url: 'https://www.ebay.com/itm/sample-6',
    imageUrl: null,
    seller: 'eldraine_singles',
  },
  {
    id: 'sample-7',
    title: 'Mana Crypt Eternal Masters MTG Heavily Played - make offer',
    askingPrice: 85,
    bestOfferEnabled: true,
    condition: 'heavily_played',
    shippingCost: 5,
    quantity: 1,
    cardName: 'Mana Crypt',
    setHint: 'Eternal Masters',
    foil: false,
    url: 'https://www.ebay.com/itm/sample-7',
    imageUrl: null,
    seller: 'vintage_vault',
  },
  {
    id: 'sample-8',
    title: 'Esper Sentinel Modern Horizons 2 MTG NM x1 best offer welcome',
    askingPrice: 26,
    bestOfferEnabled: true,
    condition: 'near_mint',
    shippingCost: 0,
    quantity: 1,
    cardName: 'Esper Sentinel',
    setHint: 'Modern Horizons 2',
    foil: false,
    url: 'https://www.ebay.com/itm/sample-8',
    imageUrl: null,
    seller: 'horizon_cards',
  },
]
