import {
  isDirectSalesSchemaMissing,
  type DirectSaleOrderRow,
} from '@/lib/direct-sales'
import {
  isEscrowSchemaMissing,
  type TradeParticipantRow,
  type TradeTransactionRow,
} from '@/lib/escrow/foundation'
import {
  isProfileSchemaMissing,
  type PrivateProfile,
  type PublicProfile,
} from '@/lib/profiles'
import {
  isInventoryStatusCompleted,
  normalizeInventoryStatus,
} from '@/lib/decks/inventory-status'

type DeckRow = {
  id: number
  user_id?: string | null
  name?: string | null
  commander?: string | null
  inventory_status?: string | null
  price_total_usd_foil?: number | null
}

type ProfileRow = PublicProfile
type PrivateProfileRow = PrivateProfile

type TransitFeedItem = {
  id: string
  deckKey: string
  deckId?: number | null
  deckLabel: string
  flow: 'Direct Sale' | 'Trade Escrow'
  fromLabel: string
  toLabel: string
  toWarehouseSlug?: WarehouseSlug
  trackingReference: string
  trackingSourceLabel: string
  autoGenerated: boolean
  statusLabel: string
  shippedAt?: string | null
  href: string
}

type WarehouseSlug = 'sarnia' | 'port-huron'
type SupportedCountryCode = 'ca' | 'us'

type WarehouseSummary = {
  slug: WarehouseSlug
  city: string
  countryCode: SupportedCountryCode
  countryLabel: string
  count: number
}

type CountrySummary = {
  countryCode: SupportedCountryCode
  countryLabel: string
  count: number
  totalValueUsd: number
}

type LogisticsMetric = {
  label: string
  value: number
  accent: string
}

type IntakeQueueItem = {
  tradeId: number
  side: 'a' | 'b'
  deckId?: number | null
  deckLabel: string
  warehouseSlug: WarehouseSlug
  warehouseLabel: string
  receivedAt?: string | null
  inspectionStatus?: string | null
  href: string
}

export type AdminLogisticsSnapshot = {
  warehouses: WarehouseSummary[]
  inTransit: TransitFeedItem[]
  usersByCountry: CountrySummary[]
  intakeQueue: IntakeQueueItem[]
  metrics: LogisticsMetric[]
  schemaWarnings: string[]
  crossDockCount: number
  unknownCountryCount: number
}

const WAREHOUSES: Record<WarehouseSlug, Omit<WarehouseSummary, 'count'>> = {
  sarnia: {
    slug: 'sarnia',
    city: 'Sarnia',
    countryCode: 'ca',
    countryLabel: 'Canada',
  },
  'port-huron': {
    slug: 'port-huron',
    city: 'Port Huron',
    countryCode: 'us',
    countryLabel: 'USA',
  },
}

function normalizeCountry(value?: string | null): SupportedCountryCode | null {
  const normalized = value?.trim().toLowerCase()

  if (!normalized) return null
  if (
    normalized === 'ca' ||
    normalized === 'canada'
  ) {
    return 'ca'
  }

  if (
    normalized === 'us' ||
    normalized === 'usa' ||
    normalized === 'united states' ||
    normalized === 'united states of america'
  ) {
    return 'us'
  }

  return null
}

function countryLabel(code: SupportedCountryCode) {
  return code === 'ca' ? 'Canada' : 'USA'
}

function warehouseSlugForCountry(code: SupportedCountryCode): WarehouseSlug {
  return code === 'ca' ? 'sarnia' : 'port-huron'
}

function warehouseLabelForCountry(code: SupportedCountryCode) {
  const warehouse = WAREHOUSES[warehouseSlugForCountry(code)]
  return `${warehouse.city}, ${warehouse.countryLabel}`
}

function deckLabel(deck?: Pick<DeckRow, 'id' | 'name' | 'commander'> | null, fallback?: string) {
  if (deck?.name?.trim()) return deck.name.trim()
  if (deck?.commander?.trim()) return deck.commander.trim()
  if (deck?.id) return `Deck #${deck.id}`
  return fallback ?? 'Unlinked deck'
}

function buildTrackingReference(input: {
  trackingCode?: string | null
  type: 'DS' | 'TR'
  id: number
  side?: string
  country?: SupportedCountryCode | null
}) {
  const provided = input.trackingCode?.trim()
  if (provided) {
    return {
      trackingReference: provided,
      trackingSourceLabel: 'Carrier tracking',
      autoGenerated: false,
    }
  }

  const countryPart = (input.country ?? 'ca').toUpperCase()
  const sidePart = input.side ? `-${input.side.toUpperCase()}` : ''

  return {
    trackingReference: `DSP-${input.type}-${countryPart}-${String(input.id).padStart(6, '0')}${sidePart}`,
    trackingSourceLabel: 'Shipping partner auto-generated',
    autoGenerated: true,
  }
}

function compareByShippedAt(left: TransitFeedItem, right: TransitFeedItem) {
  return (
    new Date(right.shippedAt ?? 0).getTime() - new Date(left.shippedAt ?? 0).getTime()
  )
}

export async function getAdminLogisticsSnapshot(supabase: {
  from: (table: string) => any
}) {
  const [
    decksResult,
    profilesResult,
    privateProfilesResult,
    directSaleOrdersResult,
    tradeTransactionsResult,
    tradeParticipantsResult,
  ] = await Promise.all([
    supabase
      .from('decks')
      .select('id, user_id, name, commander, inventory_status, price_total_usd_foil')
      .order('id', { ascending: true }),
    supabase
      .from('profiles')
      .select('user_id, location_country')
      .order('user_id', { ascending: true }),
    supabase
      .from('profile_private')
      .select('user_id, shipping_country')
      .order('user_id', { ascending: true }),
    supabase
      .from('direct_sale_orders')
      .select(
        'id, deck_id, seller_user_id, buyer_user_id, order_type, status, tracking_code, shipped_at, shipping_label_addon_usd, label_box_requested, created_at'
      )
      .order('created_at', { ascending: false }),
    supabase
      .from('trade_transactions')
      .select('id, status, created_at')
      .order('created_at', { ascending: false }),
    supabase
      .from('trade_transaction_participants')
      .select('transaction_id, side, deck_id, country_code, shipment_status, tracking_code, shipped_at, received_at')
      .order('transaction_id', { ascending: false }),
  ])

  const schemaWarnings: string[] = []

  if (isProfileSchemaMissing(profilesResult.error?.message) || isProfileSchemaMissing(privateProfilesResult.error?.message)) {
    schemaWarnings.push('Profile geography is partially unavailable, so some country counts may be understated.')
  }

  if (isDirectSalesSchemaMissing(directSaleOrdersResult.error?.message)) {
    schemaWarnings.push('Direct-sale shipment data is unavailable until the direct-sale orders schema is enabled.')
  }

  if (
    isEscrowSchemaMissing(tradeTransactionsResult.error?.message) ||
    isEscrowSchemaMissing(tradeParticipantsResult.error?.message)
  ) {
    schemaWarnings.push('Trade escrow shipment data is unavailable until the escrow schema is enabled.')
  }

  const decks = (decksResult.data ?? []) as DeckRow[]
  const profiles = (profilesResult.data ?? []) as ProfileRow[]
  const privateProfiles = (privateProfilesResult.data ?? []) as PrivateProfileRow[]
  const directSaleOrders = (directSaleOrdersResult.data ?? []) as DirectSaleOrderRow[]
  const tradeTransactions = (tradeTransactionsResult.data ?? []) as TradeTransactionRow[]
  const tradeParticipants = (tradeParticipantsResult.data ?? []) as TradeParticipantRow[]

  const deckById = new Map<number, DeckRow>(decks.map((deck) => [deck.id, deck]))
  const publicCountryByUser = new Map<string, SupportedCountryCode | null>(
    profiles.map((profile) => [profile.user_id, normalizeCountry(profile.location_country)])
  )
  const privateCountryByUser = new Map<string, SupportedCountryCode | null>(
    privateProfiles.map((profile) => [profile.user_id, normalizeCountry(profile.shipping_country)])
  )
  const tradeById = new Map<number, TradeTransactionRow>(
    tradeTransactions.map((trade) => [trade.id, trade])
  )
  const tradeCountryByDeck = new Map<number, SupportedCountryCode | null>()

  for (const participant of tradeParticipants) {
    if (participant.deck_id) {
      tradeCountryByDeck.set(
        participant.deck_id,
        normalizeCountry(participant.country_code)
      )
    }
  }

  function resolveDeckCountry(deck?: DeckRow | null) {
    if (!deck?.user_id) return tradeCountryByDeck.get(deck?.id ?? 0) ?? null
    return (
      privateCountryByUser.get(deck.user_id) ??
      publicCountryByUser.get(deck.user_id) ??
      tradeCountryByDeck.get(deck.id) ??
      null
    )
  }

  const onSiteCounts = new Map<WarehouseSlug, number>([
    ['sarnia', 0],
    ['port-huron', 0],
  ])
  const inUsersHands = new Map<SupportedCountryCode, CountrySummary>([
    ['ca', { countryCode: 'ca', countryLabel: 'Canada', count: 0, totalValueUsd: 0 }],
    ['us', { countryCode: 'us', countryLabel: 'USA', count: 0, totalValueUsd: 0 }],
  ])
  const onSiteKeys = new Set<string>()
  const inTransitKeys = new Set<string>()
  const intakeQueue: IntakeQueueItem[] = []
  let unknownCountryCount = 0
  let crossDockCount = 0

  const transitFeed: TransitFeedItem[] = []

  for (const order of directSaleOrders) {
    if (order.status !== 'shipped') continue

    const deck = deckById.get(order.deck_id) ?? null
    const sellerCountry =
      normalizeCountry(order.seller_user_id ? privateCountryByUser.get(order.seller_user_id) ?? publicCountryByUser.get(order.seller_user_id) ?? null : null)
    const buyerCountry =
      normalizeCountry(order.buyer_user_id ? privateCountryByUser.get(order.buyer_user_id) ?? publicCountryByUser.get(order.buyer_user_id) ?? null : null)
    const tracking = buildTrackingReference({
      trackingCode: order.tracking_code,
      type: 'DS',
      id: order.id,
      country: sellerCountry,
    })
    const deckKey = `deck:${order.deck_id}`

    inTransitKeys.add(deckKey)
    if (sellerCountry && buyerCountry && sellerCountry !== buyerCountry) {
      crossDockCount += 1
    }

    transitFeed.push({
      id: `direct-sale:${order.id}`,
      deckKey,
      deckId: order.deck_id,
      deckLabel: deckLabel(deck, `Order #${order.id}`),
      flow: 'Direct Sale',
      fromLabel: sellerCountry ? `${countryLabel(sellerCountry)} user inventory` : 'Seller inventory',
      toLabel: buyerCountry ? `${countryLabel(buyerCountry)} buyer handoff` : 'Buyer destination',
      trackingReference: tracking.trackingReference,
      trackingSourceLabel: tracking.trackingSourceLabel,
      autoGenerated: tracking.autoGenerated,
      statusLabel: 'In transit to buyer',
      shippedAt: order.shipped_at,
      href: `/orders/${order.id}`,
    })
  }

  for (const participant of tradeParticipants) {
    if (participant.shipment_status !== 'shipped' && participant.shipment_status !== 'received') {
      continue
    }

    const trade = tradeById.get(participant.transaction_id)
    const participantCountry = normalizeCountry(participant.country_code)
    const deck = participant.deck_id ? deckById.get(participant.deck_id) ?? null : null
    const deckKey = participant.deck_id
      ? `deck:${participant.deck_id}`
      : `trade:${participant.transaction_id}:${participant.side}`

    if (participant.shipment_status === 'received') {
      if (participantCountry) {
        const slug = warehouseSlugForCountry(participantCountry)
        onSiteCounts.set(slug, Number(onSiteCounts.get(slug) ?? 0) + 1)
        intakeQueue.push({
          tradeId: participant.transaction_id,
          side: participant.side,
          deckId: participant.deck_id,
          deckLabel: deckLabel(
            deck,
            `Trade #${participant.transaction_id} ${participant.side.toUpperCase()}`
          ),
          warehouseSlug: slug,
          warehouseLabel: warehouseLabelForCountry(participantCountry),
          receivedAt: participant.received_at,
          inspectionStatus: participant.inspection_status,
          href: `/admin/logistics/intake/${participant.transaction_id}/${participant.side}`,
        })
      } else {
        unknownCountryCount += 1
      }
      onSiteKeys.add(deckKey)
      continue
    }

    const tracking = buildTrackingReference({
      trackingCode: participant.tracking_code,
      type: 'TR',
      id: participant.transaction_id,
      side: participant.side,
      country: participantCountry,
    })
    const toWarehouseSlug = participantCountry
      ? warehouseSlugForCountry(participantCountry)
      : undefined

    inTransitKeys.add(deckKey)

    transitFeed.push({
      id: `trade:${participant.transaction_id}:${participant.side}`,
      deckKey,
      deckId: participant.deck_id,
      deckLabel: deckLabel(deck, `Trade #${participant.transaction_id} ${participant.side.toUpperCase()}`),
      flow: 'Trade Escrow',
      fromLabel: participantCountry
        ? `${countryLabel(participantCountry)} user inventory`
        : `Trader ${participant.side.toUpperCase()} inventory`,
      toLabel: participantCountry
        ? warehouseLabelForCountry(participantCountry)
        : 'Escrow hub',
      toWarehouseSlug,
      trackingReference: tracking.trackingReference,
      trackingSourceLabel: tracking.trackingSourceLabel,
      autoGenerated: tracking.autoGenerated,
      statusLabel:
        trade?.status === 'in_transit' ? 'Inbound to warehouse' : 'Shipped to warehouse',
      shippedAt: participant.shipped_at,
      href: `/trades/${participant.transaction_id}`,
    })
  }

  for (const deck of decks) {
    const deckKey = `deck:${deck.id}`
    const status = normalizeInventoryStatus(deck.inventory_status)

    if (status === 'escrow_received' || status === 'escrow_review' || status === 'holiday_received') {
      if (onSiteKeys.has(deckKey)) continue

      const country = resolveDeckCountry(deck)
      if (country) {
        const slug = warehouseSlugForCountry(country)
        onSiteCounts.set(slug, Number(onSiteCounts.get(slug) ?? 0) + 1)
      } else {
        unknownCountryCount += 1
      }
      onSiteKeys.add(deckKey)
      continue
    }

    if (inTransitKeys.has(deckKey) || onSiteKeys.has(deckKey) || isInventoryStatusCompleted(status)) {
      continue
    }

    const country = resolveDeckCountry(deck)
    if (!country) {
      unknownCountryCount += 1
      continue
    }

    const summary = inUsersHands.get(country)
    if (!summary) continue

    summary.count += 1
    summary.totalValueUsd += Number(deck.price_total_usd_foil ?? 0)
  }

  const warehouses = (Object.values(WAREHOUSES) as Array<Omit<WarehouseSummary, 'count'>>).map(
    (warehouse) => ({
      ...warehouse,
      count: Number(onSiteCounts.get(warehouse.slug) ?? 0),
    })
  )

  const usersByCountry = [...inUsersHands.values()].sort((left, right) => right.count - left.count)
  const inTransit = transitFeed.sort(compareByShippedAt)
  const metrics: LogisticsMetric[] = [
    {
      label: 'Decks on site',
      value: warehouses.reduce((sum, warehouse) => sum + warehouse.count, 0),
      accent: 'text-emerald-300',
    },
    {
      label: 'Decks in transit',
      value: inTransit.length,
      accent: 'text-sky-300',
    },
    {
      label: 'Decks in users hands',
      value: usersByCountry.reduce((sum, item) => sum + item.count, 0),
      accent: 'text-amber-200',
    },
    {
      label: 'Cross-border active lanes',
      value: crossDockCount,
      accent: 'text-fuchsia-200',
    },
  ]

  return {
    warehouses,
    inTransit,
    usersByCountry,
    intakeQueue: intakeQueue.sort(
      (left, right) =>
        new Date(right.receivedAt ?? 0).getTime() - new Date(left.receivedAt ?? 0).getTime()
    ),
    metrics,
    schemaWarnings,
    crossDockCount,
    unknownCountryCount,
  } satisfies AdminLogisticsSnapshot
}
