alter table public.auction_listings
  add column if not exists settlement_mode text not null default 'managed',
  add column if not exists winner_acknowledged_at timestamptz,
  add column if not exists seller_acknowledged_at timestamptz,
  add column if not exists buyer_payment_marked_at timestamptz,
  add column if not exists seller_fulfillment_marked_at timestamptz,
  add column if not exists buyer_received_marked_at timestamptz,
  add column if not exists settled_at timestamptz,
  add column if not exists dispute_opened_at timestamptz,
  add column if not exists dispute_resolved_at timestamptz,
  add column if not exists dispute_summary text;

alter table public.auction_listings
  drop constraint if exists auction_listings_status_check;

alter table public.auction_listings
  add constraint auction_listings_status_check
  check (status in ('active', 'pending_confirmation', 'awaiting_payment', 'paid', 'shipped', 'delivered', 'payout_released', 'awaiting_settlement', 'under_arbitration', 'completed', 'cancelled', 'expired'));

alter table public.auction_listings
  drop constraint if exists auction_listings_settlement_mode_check;

alter table public.auction_listings
  add constraint auction_listings_settlement_mode_check
  check (settlement_mode in ('managed', 'self_cleared'));

drop index if exists public.auction_listings_one_open_auction_per_deck_idx;

create unique index if not exists auction_listings_one_open_auction_per_deck_idx
  on public.auction_listings (deck_id)
  where status in ('active', 'pending_confirmation', 'awaiting_payment', 'paid', 'shipped', 'delivered', 'awaiting_settlement', 'under_arbitration');

create table if not exists public.auction_arbitration_cases (
  id bigint generated by default as identity primary key,
  auction_id bigint not null references public.auction_listings(id) on delete cascade,
  requested_by_user_id uuid not null references auth.users(id) on delete cascade,
  counterparty_user_id uuid references auth.users(id) on delete set null,
  status text not null default 'open',
  issue_type text not null,
  requested_action text,
  claimant_statement text not null,
  respondent_statement text,
  evidence_summary text,
  internal_notes text,
  outcome text,
  last_checkpoint text,
  resolution_deadline_at timestamptz,
  resolved_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (status in ('open', 'in_review', 'resolved', 'closed')),
  check (issue_type in ('non_payment', 'non_delivery', 'item_not_as_described', 'damaged', 'communication_breakdown', 'other'))
);

create index if not exists auction_arbitration_cases_auction_created_at_idx
  on public.auction_arbitration_cases (auction_id, created_at desc);

create index if not exists auction_arbitration_cases_status_created_at_idx
  on public.auction_arbitration_cases (status, created_at desc);

alter table public.auction_arbitration_cases enable row level security;

drop policy if exists "auction arbitration cases readable by participants and admin"
  on public.auction_arbitration_cases;

create policy "auction arbitration cases readable by participants and admin"
  on public.auction_arbitration_cases
  for select
  using (
    exists (
      select 1
      from public.auction_listings listing
      where listing.id = auction_id
        and (
          listing.seller_user_id = auth.uid()
          or listing.current_high_bidder_user_id = auth.uid()
          or listing.winner_user_id = auth.uid()
          or auth.jwt() ->> 'email' = 'tim.felsky@gmail.com'
        )
    )
  );

drop policy if exists "auction arbitration cases inserted by participants and admin"
  on public.auction_arbitration_cases;

create policy "auction arbitration cases inserted by participants and admin"
  on public.auction_arbitration_cases
  for insert
  with check (
    requested_by_user_id = auth.uid()
    and exists (
      select 1
      from public.auction_listings listing
      where listing.id = auction_id
        and (
          listing.seller_user_id = auth.uid()
          or listing.current_high_bidder_user_id = auth.uid()
          or listing.winner_user_id = auth.uid()
          or auth.jwt() ->> 'email' = 'tim.felsky@gmail.com'
        )
    )
  );

drop policy if exists "auction arbitration cases updated by admin"
  on public.auction_arbitration_cases;

create policy "auction arbitration cases updated by admin"
  on public.auction_arbitration_cases
  for update
  using (auth.jwt() ->> 'email' = 'tim.felsky@gmail.com')
  with check (auth.jwt() ->> 'email' = 'tim.felsky@gmail.com');
