create table if not exists public.support_tickets (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  resolved_at timestamptz,
  user_id uuid references auth.users (id) on delete set null,
  email text not null,
  name text,
  subject text not null,
  category text not null default 'general' check (category in ('bug', 'trade', 'order', 'listing', 'account', 'billing', 'general')),
  priority text not null default 'normal' check (priority in ('low', 'normal', 'high', 'urgent')),
  status text not null default 'open' check (status in ('open', 'in_progress', 'resolved', 'closed')),
  description text not null,
  url_path text,
  admin_notes text
);

create index if not exists support_tickets_user_id_idx on public.support_tickets (user_id);
create index if not exists support_tickets_status_idx on public.support_tickets (status);
create index if not exists support_tickets_created_at_idx on public.support_tickets (created_at desc);

create or replace function public.set_support_tickets_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());

  if new.status in ('resolved', 'closed') and old.status is distinct from new.status then
    new.resolved_at = timezone('utc', now());
  elsif new.status not in ('resolved', 'closed') then
    new.resolved_at = null;
  end if;

  return new;
end;
$$;

drop trigger if exists support_tickets_set_updated_at on public.support_tickets;

create trigger support_tickets_set_updated_at
before update on public.support_tickets
for each row
execute function public.set_support_tickets_updated_at();
