-- Trade Network Link-Up: opt-in community network that pools members' aged
-- high-end singles inventory and proposes balanced owner-to-owner swaps via
-- lib/wholesale-turnover. Idempotent: create-if-not-exists / drop-policy-
-- if-exists guards make it safe to re-run.

create table if not exists public.trade_network_memberships (
  user_id uuid primary key references auth.users(id) on delete cascade,
  enabled boolean not null default true,
  display_name text,
  country text,
  min_item_value_usd numeric not null default 50,
  minimum_age_days integer not null default 120,
  wanted_categories text[] not null default '{}'::text[],
  blocked_user_ids uuid[] not null default '{}'::uuid[],
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (min_item_value_usd >= 0),
  check (minimum_age_days >= 0)
);

create table if not exists public.trade_network_linkups (
  id bigint generated by default as identity primary key,
  initiated_by_user_id uuid not null references auth.users(id) on delete cascade,
  counterparty_user_id uuid not null references auth.users(id) on delete cascade,
  status text not null default 'pending',
  message text,
  -- Snapshot of the WholesaleTurnoverProposal the request was generated from,
  -- so both sides can review the exact bundles even after inventory moves.
  proposal jsonb not null,
  responded_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (status in ('pending', 'accepted', 'declined', 'withdrawn')),
  check (initiated_by_user_id <> counterparty_user_id)
);

create index if not exists trade_network_linkups_initiated_by_idx
  on public.trade_network_linkups (initiated_by_user_id, created_at desc);

create index if not exists trade_network_linkups_counterparty_idx
  on public.trade_network_linkups (counterparty_user_id, created_at desc);

alter table public.trade_network_memberships enable row level security;
alter table public.trade_network_linkups enable row level security;

drop policy if exists "users read own trade network membership"
  on public.trade_network_memberships;

create policy "users read own trade network membership"
  on public.trade_network_memberships
  for select
  using (auth.uid() = user_id or auth.jwt() ->> 'email' = 'tim.felsky@gmail.com');

drop policy if exists "users manage own trade network membership"
  on public.trade_network_memberships;

create policy "users manage own trade network membership"
  on public.trade_network_memberships
  for all
  using (auth.uid() = user_id or auth.jwt() ->> 'email' = 'tim.felsky@gmail.com')
  with check (auth.uid() = user_id or auth.jwt() ->> 'email' = 'tim.felsky@gmail.com');

drop policy if exists "participants read their trade network linkups"
  on public.trade_network_linkups;

create policy "participants read their trade network linkups"
  on public.trade_network_linkups
  for select
  using (
    initiated_by_user_id = auth.uid()
    or counterparty_user_id = auth.uid()
    or auth.jwt() ->> 'email' = 'tim.felsky@gmail.com'
  );

drop policy if exists "users create their own trade network linkups"
  on public.trade_network_linkups;

create policy "users create their own trade network linkups"
  on public.trade_network_linkups
  for insert
  with check (
    initiated_by_user_id = auth.uid()
    and initiated_by_user_id <> counterparty_user_id
  );

drop policy if exists "participants update their trade network linkups"
  on public.trade_network_linkups;

create policy "participants update their trade network linkups"
  on public.trade_network_linkups
  for update
  using (
    initiated_by_user_id = auth.uid()
    or counterparty_user_id = auth.uid()
    or auth.jwt() ->> 'email' = 'tim.felsky@gmail.com'
  )
  with check (
    initiated_by_user_id = auth.uid()
    or counterparty_user_id = auth.uid()
    or auth.jwt() ->> 'email' = 'tim.felsky@gmail.com'
  );
