create table if not exists public.deck_listing_images (
  id bigint generated by default as identity primary key,
  deck_id bigint not null references public.decks (id) on delete cascade,
  user_id uuid not null references auth.users (id) on delete cascade,
  storage_path text not null unique,
  public_url text not null,
  width integer,
  height integer,
  file_size_bytes integer,
  mime_type text,
  sort_order integer not null default 1,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists deck_listing_images_deck_id_idx
  on public.deck_listing_images (deck_id, sort_order, id);

alter table public.deck_listing_images enable row level security;

drop policy if exists "deck listing images are publicly readable"
  on public.deck_listing_images;
create policy "deck listing images are publicly readable"
  on public.deck_listing_images
  for select
  using (true);

drop policy if exists "deck listing images inserted by owner"
  on public.deck_listing_images;
create policy "deck listing images inserted by owner"
  on public.deck_listing_images
  for insert
  with check (auth.uid() = user_id);

drop policy if exists "deck listing images updated by owner"
  on public.deck_listing_images;
create policy "deck listing images updated by owner"
  on public.deck_listing_images
  for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "deck listing images deleted by owner"
  on public.deck_listing_images;
create policy "deck listing images deleted by owner"
  on public.deck_listing_images
  for delete
  using (auth.uid() = user_id);

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'deck-listing-images',
  'deck-listing-images',
  true,
  1500000,
  array['image/jpeg', 'image/png', 'image/webp']
)
on conflict (id) do update
set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;
