-- Queue My Order: singles mail slots.
--
-- A buyer can pay for singles now and have the seller hold them instead of
-- shipping. Held orders sit in a "mail slot" — one open slot per buyer + seller —
-- and every later queued order from that seller drops into the same slot. The
-- whole slot ships once, with one combined shipping charge, when the buyer
-- releases it or the paid-up hold runs out (/api/cron/release-mail-slots settles
-- lapsed holds daily; the seller can also ship a lapsed slot directly).
--
-- The buyer rents the slot from the seller in whole weeks: $1/week, capped at 13
-- weeks from opening so the shipment lands well inside the ~120-day card-network
-- chargeback window. lib/singles/mail-slots.ts mirrors these numbers for quotes;
-- this file is the source of truth. Every state change runs through the
-- security-definer functions below — the new tables only carry read policies.
--
-- Idempotent: create-if-not-exists / drop-if-exists guards make it safe to re-run.

create table if not exists public.singles_mail_slots (
  id bigint generated by default as identity primary key,
  buyer_user_id uuid not null references auth.users(id) on delete cascade,
  seller_user_id uuid not null references auth.users(id) on delete cascade,
  status text not null default 'open',
  opened_at timestamptz not null default now(),
  held_until timestamptz not null,
  max_hold_until timestamptz not null,
  weeks_purchased integer not null default 0,
  rent_paid_usd numeric not null default 0,
  release_reason text,
  released_at timestamptz,
  shipping_method text,
  shipping_amount_usd numeric,
  tracking_code text,
  shipped_at timestamptz,
  delivered_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (status in ('open', 'ready_to_ship', 'shipped', 'delivered')),
  check (release_reason is null or release_reason in ('buyer_request', 'hold_expired')),
  check (held_until <= max_hold_until)
);

-- Queued orders from the same seller always land in the same slot.
create unique index if not exists singles_mail_slots_one_open_per_pair
  on public.singles_mail_slots (buyer_user_id, seller_user_id)
  where status = 'open';

create index if not exists singles_mail_slots_buyer_idx
  on public.singles_mail_slots (buyer_user_id, created_at desc);

create index if not exists singles_mail_slots_seller_idx
  on public.singles_mail_slots (seller_user_id, created_at desc);

create index if not exists singles_mail_slots_lapsed_idx
  on public.singles_mail_slots (status, held_until);

-- Ledger of everything a slot has cost the buyer: rent (at checkout or on
-- extension) and the one combined shipping charge when it is released.
create table if not exists public.singles_mail_slot_charges (
  id bigint generated by default as identity primary key,
  mail_slot_id bigint not null references public.singles_mail_slots(id) on delete cascade,
  order_id bigint references public.singles_orders(id) on delete set null,
  kind text not null,
  weeks integer not null default 0,
  amount_usd numeric not null default 0,
  created_at timestamptz not null default now(),
  check (kind in ('rent', 'shipping'))
);

create index if not exists singles_mail_slot_charges_slot_idx
  on public.singles_mail_slot_charges (mail_slot_id, created_at asc);

alter table public.singles_orders
  add column if not exists mail_slot_id bigint references public.singles_mail_slots(id) on delete set null,
  add column if not exists slot_rent_usd numeric not null default 0;

create index if not exists singles_orders_mail_slot_idx
  on public.singles_orders (mail_slot_id)
  where mail_slot_id is not null;

-- Add 'queued' to the order lifecycle. The original status check was unnamed,
-- so find it by definition rather than trusting the generated name.
do $$
declare
  v_constraint_name text;
begin
  for v_constraint_name in
    select conname
    from pg_constraint
    where conrelid = 'public.singles_orders'::regclass
      and contype = 'c'
      and pg_get_constraintdef(oid) like '%awaiting_shipment%'
  loop
    execute format('alter table public.singles_orders drop constraint %I', v_constraint_name);
  end loop;
end
$$;

alter table public.singles_orders
  add constraint singles_orders_status_check
  check (status in ('queued', 'awaiting_shipment', 'shipped', 'delivered', 'completed', 'cancelled'));

alter table public.singles_mail_slots enable row level security;
alter table public.singles_mail_slot_charges enable row level security;

drop policy if exists "buyers and sellers read mail slots"
  on public.singles_mail_slots;

create policy "buyers and sellers read mail slots"
  on public.singles_mail_slots
  for select
  using (
    auth.uid() = buyer_user_id
    or auth.uid() = seller_user_id
    or auth.jwt() ->> 'email' = 'tim.felsky@gmail.com'
  );

drop policy if exists "buyers and sellers read mail slot charges"
  on public.singles_mail_slot_charges;

create policy "buyers and sellers read mail slot charges"
  on public.singles_mail_slot_charges
  for select
  using (
    exists (
      select 1
      from public.singles_mail_slots slots
      where slots.id = mail_slot_id
        and (
          slots.buyer_user_id = auth.uid()
          or slots.seller_user_id = auth.uid()
          or auth.jwt() ->> 'email' = 'tim.felsky@gmail.com'
        )
    )
  );

-- Whole weeks of rent a slot can still take. Extensions stack on the later of the
-- paid-through date and now, so a lapsed hold restarts from today.
create or replace function public.singles_mail_slot_remaining_weeks(
  p_held_until timestamptz,
  p_max_hold_until timestamptz
)
returns integer
language sql
stable
as $$
  select greatest(
    0,
    floor(extract(epoch from (p_max_hold_until - greatest(p_held_until, now()))) / 604800)
  )::integer
$$;

-- Checkout, now with an optional mail slot. Adding parameters changes the
-- signature, so drop the three-arg version first to avoid an ambiguous overload.
drop function if exists public.create_singles_checkout(uuid, jsonb, integer);

create or replace function public.create_singles_checkout(
  p_buyer_user_id uuid,
  p_cart_items jsonb,
  p_redeem_points integer default 0,
  p_queue_in_mail_slot boolean default false,
  p_hold_weeks integer default 0
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_rent_per_week_usd constant numeric := 1;
  v_max_hold_weeks constant integer := 13;
  v_item record;
  v_listing record;
  v_order_id bigint;
  v_subtotal numeric := 0;
  v_discount_amount numeric := 0;
  v_discounted_subtotal numeric := 0;
  v_shipping_amount numeric := 0;
  v_tax_amount numeric := 0;
  v_grand_total numeric := 0;
  v_discount_tier_key text := 'none';
  v_discount_tier_label text := 'No volume discount yet';
  v_seller_user_id uuid := null;
  v_item_count integer := 0;
  v_line_subtotal numeric := 0;
  v_price numeric := 0;
  v_available integer := 0;
  v_shipping_method text := 'pwe_untracked';
  v_shipping_label text := 'PWE Plain White Envelope';
  v_shipping_description text := 'No tracking. Available for up to 10 cards when the order stays at $30 or less in Canada.';
  v_max_credit_usd numeric := 0;
  v_redeem_points integer := 0;
  v_points_spent integer := 0;
  v_points_credit_usd numeric := 0;
  v_queued boolean := coalesce(p_queue_in_mail_slot, false);
  v_slot record;
  v_slot_id bigint := null;
  v_hold_weeks integer := 0;
  v_remaining_weeks integer := 0;
  v_slot_rent numeric := 0;
  v_deferred_shipping numeric := 0;
  v_held_until timestamptz := null;
begin
  if p_buyer_user_id is null then
    raise exception 'A signed-in buyer is required.';
  end if;

  -- This runs as security definer, so pin the buyer to the caller. The service
  -- role (no auth.uid()) may still check out on a user's behalf.
  if auth.uid() is distinct from p_buyer_user_id
    and coalesce(auth.jwt() ->> 'role', '') <> 'service_role'
  then
    raise exception 'You can only check out as yourself.';
  end if;

  if p_cart_items is null or jsonb_typeof(p_cart_items) <> 'array' or jsonb_array_length(p_cart_items) = 0 then
    raise exception 'Your cart is empty.';
  end if;

  create temporary table temp_checkout_items (
    single_inventory_item_id bigint not null,
    quantity integer not null
  ) on commit drop;

  insert into temp_checkout_items (single_inventory_item_id, quantity)
  select
    (item ->> 'singleInventoryItemId')::bigint,
    greatest(1, floor((item ->> 'quantity')::numeric))::integer
  from jsonb_array_elements(p_cart_items) item;

  delete from temp_checkout_items
  where single_inventory_item_id is null or quantity <= 0;

  if not exists (select 1 from temp_checkout_items) then
    raise exception 'Your cart does not contain any valid items.';
  end if;

  for v_item in
    select single_inventory_item_id, sum(quantity)::integer as quantity
    from temp_checkout_items
    group by single_inventory_item_id
    order by single_inventory_item_id
  loop
    select *
    into v_listing
    from public.single_inventory_items
    where id = v_item.single_inventory_item_id
    for update;

    if not found then
      raise exception 'One of the selected singles could not be found.';
    end if;

    if v_listing.marketplace_visible is distinct from true
      or v_listing.marketplace_status <> 'active'
      or coalesce(v_listing.marketplace_price_usd, 0) <= 0
      or coalesce(v_listing.marketplace_quantity_available, 0) <= 0
      or v_listing.inventory_status <> 'buy_it_now_live'
    then
      raise exception '% is no longer available for checkout.', v_listing.card_name;
    end if;

    if v_seller_user_id is null then
      v_seller_user_id := v_listing.user_id;
    elsif v_seller_user_id <> v_listing.user_id then
      raise exception 'For now, checkout supports singles from one seller at a time.';
    end if;

    v_available := greatest(0, coalesce(v_listing.marketplace_quantity_available, 0));
    if v_available < v_item.quantity then
      raise exception '% only has % copy/copies available right now.', v_listing.card_name, v_available;
    end if;

    v_price := round(coalesce(v_listing.marketplace_price_usd, 0)::numeric, 2);
    v_line_subtotal := round(v_price * v_item.quantity, 2);
    v_subtotal := round(v_subtotal + v_line_subtotal, 2);
    v_item_count := v_item_count + v_item.quantity;
  end loop;

  if v_subtotal >= 200 then
    v_discount_tier_key := 'tier_25';
    v_discount_tier_label := '25% off orders $200+';
    v_discount_amount := round(v_subtotal * 0.25, 2);
  elsif v_subtotal >= 100 then
    v_discount_tier_key := 'tier_20';
    v_discount_tier_label := '20% off orders $100+';
    v_discount_amount := round(v_subtotal * 0.20, 2);
  else
    v_discount_amount := 0;
  end if;

  v_discounted_subtotal := round(v_subtotal - v_discount_amount, 2);
  if v_subtotal > 30 or v_item_count > 10 then
    v_shipping_method := 'tracked_padded_mailer';
    v_shipping_label := 'Padded mailer with tracking';
    v_shipping_description := 'Automatic for orders over $30 or more than 10 cards in Canada.';
    v_shipping_amount := 15;
  else
    v_shipping_method := 'pwe_untracked';
    v_shipping_label := 'PWE Plain White Envelope';
    v_shipping_description := 'No tracking. Available for up to 10 cards when the order stays at $30 or less in Canada.';
    v_shipping_amount := 5;
  end if;
  v_grand_total := round(v_discounted_subtotal + v_shipping_amount + v_tax_amount, 2);

  -- Queue My Order: the order's own shipping is dropped (the slot pays one
  -- combined charge when it ships) and rent for any weeks bought now is added.
  -- The slot row is locked so a concurrent release or shipment can't race a join.
  if v_queued then
    v_deferred_shipping := v_shipping_amount;
    v_shipping_amount := 0;
    v_shipping_method := 'mail_slot';
    v_shipping_label := 'Held in your mail slot';
    v_shipping_description := 'Ships with everything else in your mail slot. Combined shipping is charged once, when the slot ships.';

    select *
    into v_slot
    from public.singles_mail_slots
    where buyer_user_id = p_buyer_user_id
      and seller_user_id = v_seller_user_id
      and status = 'open'
    for update;

    if found then
      v_slot_id := v_slot.id;
      v_remaining_weeks := public.singles_mail_slot_remaining_weeks(v_slot.held_until, v_slot.max_hold_until);
      v_hold_weeks := greatest(0, coalesce(p_hold_weeks, 0));

      if v_hold_weeks > v_remaining_weeks then
        raise exception 'Your mail slot with this seller can only be extended % more week(s).', v_remaining_weeks;
      end if;

      v_slot_rent := round(v_hold_weeks * v_rent_per_week_usd, 2);
      v_held_until := v_slot.held_until;

      if v_hold_weeks > 0 then
        v_held_until := greatest(v_slot.held_until, now()) + make_interval(weeks => v_hold_weeks);

        update public.singles_mail_slots
        set
          held_until = v_held_until,
          weeks_purchased = weeks_purchased + v_hold_weeks,
          rent_paid_usd = rent_paid_usd + v_slot_rent,
          updated_at = now()
        where id = v_slot_id;
      end if;
    else
      v_hold_weeks := coalesce(p_hold_weeks, 0);

      if v_hold_weeks < 1 or v_hold_weeks > v_max_hold_weeks then
        raise exception 'Choose a hold between 1 and % weeks to open a mail slot.', v_max_hold_weeks;
      end if;

      v_slot_rent := round(v_hold_weeks * v_rent_per_week_usd, 2);
      v_held_until := now() + make_interval(weeks => v_hold_weeks);

      insert into public.singles_mail_slots (
        buyer_user_id,
        seller_user_id,
        held_until,
        max_hold_until,
        weeks_purchased,
        rent_paid_usd
      )
      values (
        p_buyer_user_id,
        v_seller_user_id,
        v_held_until,
        now() + make_interval(weeks => v_max_hold_weeks),
        v_hold_weeks,
        v_slot_rent
      )
      returning id into v_slot_id;
    end if;

    v_grand_total := round(v_discounted_subtotal + v_shipping_amount + v_tax_amount + v_slot_rent, 2);
  end if;

  -- Resolve any reward-point redemption against the live total, then spend the
  -- points inside this transaction. redeem_reward_points locks the balance row and
  -- raises if it is insufficient, which rolls the whole checkout back.
  if coalesce(p_redeem_points, 0) > 0 then
    v_max_credit_usd := floor(v_grand_total * 0.5);               -- max 50% of order
    v_redeem_points := least(greatest(0, p_redeem_points), (v_max_credit_usd * 100)::integer);
    v_redeem_points := (floor(v_redeem_points / 100) * 100)::integer; -- whole-dollar increments
    if v_redeem_points >= 500 then                                -- minimum redemption
      v_points_spent := public.redeem_reward_points(
        p_buyer_user_id, v_redeem_points, 'singles_order', null, 500
      );
      v_points_credit_usd := round(v_points_spent / 100.0, 2);
      v_grand_total := round(v_grand_total - v_points_credit_usd, 2);
    end if;
  end if;

  insert into public.singles_orders (
    buyer_user_id,
    seller_user_id,
    status,
    currency,
    item_subtotal_usd,
    discount_tier_key,
    discount_tier_label,
    discount_amount_usd,
    discounted_subtotal_usd,
    shipping_amount_usd,
    tax_amount_usd,
    grand_total_usd,
    item_count,
    pricing_snapshot,
    cart_snapshot,
    mail_slot_id,
    slot_rent_usd
  )
  values (
    p_buyer_user_id,
    v_seller_user_id,
    case when v_queued then 'queued' else 'awaiting_shipment' end,
    'USD',
    v_subtotal,
    v_discount_tier_key,
    v_discount_tier_label,
    v_discount_amount,
    v_discounted_subtotal,
    v_shipping_amount,
    v_tax_amount,
    v_grand_total,
    v_item_count,
    jsonb_build_object(
      'subtotal', v_subtotal,
      'discountTier', v_discount_tier_key,
      'tierLabel', v_discount_tier_label,
      'discountAmount', v_discount_amount,
      'discountedSubtotal', v_discounted_subtotal,
      'shippingMethod', v_shipping_method,
      'shippingLabel', v_shipping_label,
      'shippingDescription', v_shipping_description,
      'shippingAmount', v_shipping_amount,
      'taxAmount', v_tax_amount,
      'pointsRedeemed', v_points_spent,
      'pointsCreditUsd', v_points_credit_usd,
      'queuedInMailSlot', v_queued,
      'mailSlotId', v_slot_id,
      'holdWeeks', v_hold_weeks,
      'slotRentUsd', v_slot_rent,
      'heldUntil', v_held_until,
      'deferredShippingUsd', v_deferred_shipping,
      'grandTotal', v_grand_total
    ),
    p_cart_items,
    v_slot_id,
    v_slot_rent
  )
  returning id into v_order_id;

  -- Backfill the redemption ledger entry's source_id now that the order exists, so
  -- it ties to the order (and dedupes against a retry of the same checkout).
  if v_points_spent > 0 then
    update public.reward_point_entries
      set source_id = v_order_id::text
      where user_id = p_buyer_user_id
        and reason = 'redemption'
        and source_type = 'singles_order'
        and source_id is null;
  end if;

  if v_slot_rent > 0 then
    insert into public.singles_mail_slot_charges (mail_slot_id, order_id, kind, weeks, amount_usd)
    values (v_slot_id, v_order_id, 'rent', v_hold_weeks, v_slot_rent);
  end if;

  for v_item in
    select single_inventory_item_id, sum(quantity)::integer as quantity
    from temp_checkout_items
    group by single_inventory_item_id
    order by single_inventory_item_id
  loop
    select *
    into v_listing
    from public.single_inventory_items
    where id = v_item.single_inventory_item_id
    for update;

    v_price := round(coalesce(v_listing.marketplace_price_usd, 0)::numeric, 2);
    v_line_subtotal := round(v_price * v_item.quantity, 2);

    insert into public.singles_order_items (
      order_id,
      single_inventory_item_id,
      seller_user_id,
      quantity,
      unit_price_usd,
      line_subtotal_usd,
      card_name,
      set_name,
      set_code,
      collector_number,
      foil,
      condition,
      language,
      image_url,
      pricing_snapshot
    )
    values (
      v_order_id,
      v_listing.id,
      v_listing.user_id,
      v_item.quantity,
      v_price,
      v_line_subtotal,
      v_listing.card_name,
      v_listing.set_name,
      v_listing.set_code,
      v_listing.collector_number,
      coalesce(v_listing.foil, false),
      v_listing.condition,
      v_listing.language,
      v_listing.image_url,
      jsonb_build_object(
        'unitPriceUsd', v_price,
        'lineSubtotalUsd', v_line_subtotal
      )
    );

    update public.single_inventory_items
    set
      marketplace_quantity_available = marketplace_quantity_available - v_item.quantity,
      marketplace_status = case
        when marketplace_quantity_available - v_item.quantity <= 0 then 'sold_out'
        else marketplace_status
      end,
      marketplace_visible = case
        when marketplace_quantity_available - v_item.quantity <= 0 then false
        else marketplace_visible
      end,
      inventory_status = case
        when marketplace_quantity_available - v_item.quantity <= 0 then 'checked_out'
        else inventory_status
      end,
      updated_at = now()
    where id = v_listing.id;
  end loop;

  return jsonb_build_object(
    'orderId', v_order_id,
    'pointsRedeemed', v_points_spent,
    'pointsCreditUsd', v_points_credit_usd,
    'mailSlotId', v_slot_id,
    'heldUntil', v_held_until
  );
end;
$$;

grant execute on function public.create_singles_checkout(uuid, jsonb, integer, boolean, integer) to authenticated;

-- Internal: close an open slot for shipping. Charges one combined shipment for
-- every queued order in it and moves those orders to awaiting_shipment. Callers
-- authorize first; a slot that is already settled is returned unchanged.
create or replace function public.settle_singles_mail_slot(p_slot_id bigint, p_reason text)
returns public.singles_mail_slots
language plpgsql
security definer
set search_path = public
as $$
declare
  v_slot public.singles_mail_slots;
  v_subtotal numeric := 0;
  v_item_count integer := 0;
  v_shipping_method text;
  v_shipping_amount numeric;
begin
  select * into v_slot from public.singles_mail_slots where id = p_slot_id for update;

  if not found then
    raise exception 'Mail slot not found.';
  end if;

  if v_slot.status <> 'open' then
    return v_slot;
  end if;

  select coalesce(sum(item_subtotal_usd), 0), coalesce(sum(item_count), 0)::integer
  into v_subtotal, v_item_count
  from public.singles_orders
  where mail_slot_id = p_slot_id
    and status = 'queued';

  -- One shipment for the whole slot, on create_singles_checkout's thresholds.
  if v_subtotal > 30 or v_item_count > 10 then
    v_shipping_method := 'tracked_padded_mailer';
    v_shipping_amount := 15;
  else
    v_shipping_method := 'pwe_untracked';
    v_shipping_amount := 5;
  end if;

  update public.singles_mail_slots
  set
    status = 'ready_to_ship',
    release_reason = p_reason,
    released_at = now(),
    shipping_method = v_shipping_method,
    shipping_amount_usd = v_shipping_amount,
    updated_at = now()
  where id = p_slot_id
  returning * into v_slot;

  insert into public.singles_mail_slot_charges (mail_slot_id, kind, amount_usd)
  values (p_slot_id, 'shipping', v_shipping_amount);

  update public.singles_orders
  set status = 'awaiting_shipment', updated_at = now()
  where mail_slot_id = p_slot_id
    and status = 'queued';

  return v_slot;
end;
$$;

revoke execute on function public.settle_singles_mail_slot(bigint, text) from public, anon, authenticated;

-- Buyer: ship my slot now. Service role (the daily cron): settle a lapsed hold.
create or replace function public.release_singles_mail_slot(p_slot_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_slot public.singles_mail_slots;
begin
  select * into v_slot from public.singles_mail_slots where id = p_slot_id for update;

  if not found then
    raise exception 'Mail slot not found.';
  end if;

  if v_slot.status <> 'open' then
    raise exception 'This mail slot has already been released.';
  end if;

  if coalesce(auth.jwt() ->> 'role', '') = 'service_role' then
    if v_slot.held_until > now() then
      raise exception 'This mail slot is still on hold.';
    end if;

    select * into v_slot from public.settle_singles_mail_slot(p_slot_id, 'hold_expired');
  elsif auth.uid() = v_slot.buyer_user_id then
    select * into v_slot from public.settle_singles_mail_slot(
      p_slot_id,
      case when v_slot.held_until > now() then 'buyer_request' else 'hold_expired' end
    );
  else
    raise exception 'Only the buyer can release this mail slot.';
  end if;

  return jsonb_build_object('mailSlot', to_jsonb(v_slot));
end;
$$;

revoke execute on function public.release_singles_mail_slot(bigint) from public, anon;
grant execute on function public.release_singles_mail_slot(bigint) to authenticated, service_role;

-- Buyer: pay more rent to keep an open slot holding, up to its 13-week cap.
create or replace function public.extend_singles_mail_slot(p_slot_id bigint, p_weeks integer)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_rent_per_week_usd constant numeric := 1;
  v_slot public.singles_mail_slots;
  v_weeks integer := coalesce(p_weeks, 0);
  v_remaining_weeks integer;
  v_rent numeric;
begin
  select * into v_slot from public.singles_mail_slots where id = p_slot_id for update;

  if not found then
    raise exception 'Mail slot not found.';
  end if;

  if auth.uid() is distinct from v_slot.buyer_user_id then
    raise exception 'Only the buyer can extend this mail slot.';
  end if;

  if v_slot.status <> 'open' then
    raise exception 'This mail slot has already been released for shipping.';
  end if;

  if v_weeks < 1 then
    raise exception 'Choose at least one week to extend the hold.';
  end if;

  v_remaining_weeks := public.singles_mail_slot_remaining_weeks(v_slot.held_until, v_slot.max_hold_until);
  if v_weeks > v_remaining_weeks then
    raise exception 'This mail slot can only be extended % more week(s); slots max out 13 weeks after opening.', v_remaining_weeks;
  end if;

  v_rent := round(v_weeks * v_rent_per_week_usd, 2);

  update public.singles_mail_slots
  set
    held_until = greatest(held_until, now()) + make_interval(weeks => v_weeks),
    weeks_purchased = weeks_purchased + v_weeks,
    rent_paid_usd = rent_paid_usd + v_rent,
    updated_at = now()
  where id = p_slot_id
  returning * into v_slot;

  insert into public.singles_mail_slot_charges (mail_slot_id, kind, weeks, amount_usd)
  values (p_slot_id, 'rent', v_weeks, v_rent);

  return jsonb_build_object('mailSlot', to_jsonb(v_slot), 'rentUsd', v_rent);
end;
$$;

revoke execute on function public.extend_singles_mail_slot(bigint, integer) from public, anon;
grant execute on function public.extend_singles_mail_slot(bigint, integer) to authenticated;

-- Seller: ship everything in the slot as one package. Allowed once the buyer has
-- released it or the paid hold has lapsed — never while the buyer is paying to hold.
create or replace function public.ship_singles_mail_slot(p_slot_id bigint, p_tracking_code text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_slot public.singles_mail_slots;
  v_tracking_code text := nullif(trim(coalesce(p_tracking_code, '')), '');
begin
  select * into v_slot from public.singles_mail_slots where id = p_slot_id for update;

  if not found then
    raise exception 'Mail slot not found.';
  end if;

  if auth.uid() is distinct from v_slot.seller_user_id then
    raise exception 'Only the seller can ship this mail slot.';
  end if;

  if v_slot.status = 'open' then
    if v_slot.held_until > now() then
      raise exception 'The buyer paid to hold this slot until %. Ship it once they release it or the hold ends.',
        to_char(v_slot.held_until, 'Mon DD, YYYY');
    end if;

    select * into v_slot from public.settle_singles_mail_slot(p_slot_id, 'hold_expired');
  end if;

  if v_slot.status <> 'ready_to_ship' then
    raise exception 'This mail slot has already shipped.';
  end if;

  update public.singles_mail_slots
  set
    status = 'shipped',
    tracking_code = v_tracking_code,
    shipped_at = now(),
    updated_at = now()
  where id = p_slot_id
  returning * into v_slot;

  update public.singles_orders
  set
    status = 'shipped',
    tracking_code = v_tracking_code,
    shipped_at = now(),
    updated_at = now()
  where mail_slot_id = p_slot_id
    and status = 'awaiting_shipment';

  return jsonb_build_object('mailSlot', to_jsonb(v_slot));
end;
$$;

revoke execute on function public.ship_singles_mail_slot(bigint, text) from public, anon;
grant execute on function public.ship_singles_mail_slot(bigint, text) to authenticated;

-- Buyer: the package arrived. Completes every order in the slot in one step and
-- returns their ids so the app can mint reward points per order.
create or replace function public.confirm_singles_mail_slot_delivered(p_slot_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_slot public.singles_mail_slots;
  v_order_ids jsonb;
begin
  select * into v_slot from public.singles_mail_slots where id = p_slot_id for update;

  if not found then
    raise exception 'Mail slot not found.';
  end if;

  if auth.uid() is distinct from v_slot.buyer_user_id then
    raise exception 'Only the buyer can confirm delivery.';
  end if;

  if v_slot.status <> 'shipped' then
    raise exception 'This mail slot is not out for delivery.';
  end if;

  with completed as (
    update public.singles_orders
    set
      status = 'completed',
      delivered_at = now(),
      completed_at = now(),
      updated_at = now()
    where mail_slot_id = p_slot_id
      and status = 'shipped'
    returning id
  )
  select coalesce(jsonb_agg(id order by id), '[]'::jsonb) into v_order_ids from completed;

  update public.singles_mail_slots
  set status = 'delivered', delivered_at = now(), updated_at = now()
  where id = p_slot_id
  returning * into v_slot;

  return jsonb_build_object('mailSlot', to_jsonb(v_slot), 'orderIds', v_order_ids);
end;
$$;

revoke execute on function public.confirm_singles_mail_slot_delivered(bigint) from public, anon;
grant execute on function public.confirm_singles_mail_slot_delivered(bigint) to authenticated;
