create table if not exists public.paper_power_nine_submissions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  credit_name text not null,
  contact_email text,
  story text not null,
  theme text,
  status text not null default 'submitted',
  card_count integer not null default 9,
  exact_match_count integer not null default 0,
  cover_image_url text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists paper_power_nine_submissions_user_id_idx
  on public.paper_power_nine_submissions (user_id, created_at desc);

create table if not exists public.paper_power_nine_submission_cards (
  id bigint generated by default as identity primary key,
  submission_id bigint not null references public.paper_power_nine_submissions (id) on delete cascade,
  user_id uuid not null references auth.users (id) on delete cascade,
  slot_number integer not null,
  submitted_name text not null,
  submitted_set_code text not null,
  submitted_collector_number text not null,
  requested_finish text not null,
  exact_print_matched boolean not null default false,
  matched_price_usd numeric(10, 2),
  scryfall_id uuid,
  oracle_id uuid,
  card_name text,
  set_code text,
  set_name text,
  collector_number text,
  artist_name text,
  released_at date,
  finishes text[] not null default '{}',
  oracle_text text,
  type_line text,
  rarity text,
  mana_cost text,
  cmc numeric(10, 2),
  power text,
  toughness text,
  color_identity text[] not null default '{}',
  keywords text[] not null default '{}',
  image_url text,
  is_legendary boolean,
  is_background boolean,
  can_be_commander boolean,
  partner_with_name text,
  artist_card_count integer,
  artist_debut_release date,
  artist_debut_set_name text,
  artist_notable_cards text[] not null default '{}',
  artist_summary text,
  top_eight_points text[] not null default '{}',
  price_usd numeric(10, 2),
  price_usd_foil numeric(10, 2),
  price_usd_etched numeric(10, 2),
  price_eur numeric(10, 2),
  price_eur_foil numeric(10, 2),
  price_tix numeric(10, 2),
  created_at timestamptz not null default timezone('utc', now()),
  constraint paper_power_nine_submission_cards_unique_slot unique (submission_id, slot_number)
);

create index if not exists paper_power_nine_submission_cards_user_id_idx
  on public.paper_power_nine_submission_cards (user_id, submission_id, slot_number);

alter table public.paper_power_nine_submissions enable row level security;
alter table public.paper_power_nine_submission_cards enable row level security;

create policy "paper power 9 submissions select own"
  on public.paper_power_nine_submissions
  for select
  to authenticated
  using (auth.uid() = user_id);

create policy "paper power 9 submissions insert own"
  on public.paper_power_nine_submissions
  for insert
  to authenticated
  with check (auth.uid() = user_id);

create policy "paper power 9 submissions update own"
  on public.paper_power_nine_submissions
  for update
  to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "paper power 9 cards select own"
  on public.paper_power_nine_submission_cards
  for select
  to authenticated
  using (auth.uid() = user_id);

create policy "paper power 9 cards insert own"
  on public.paper_power_nine_submission_cards
  for insert
  to authenticated
  with check (auth.uid() = user_id);

create policy "paper power 9 cards update own"
  on public.paper_power_nine_submission_cards
  for update
  to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);
