create table if not exists public.edhrec_card_commander_recs (
  id bigint generated by default as identity primary key,
  card_key_type text not null check (card_key_type in ('oracle_id', 'name')),
  card_key text not null,
  oracle_id uuid,
  normalized_card_name text not null,
  raw_card_name text not null,
  commander_name text,
  normalized_commander_name text,
  edhrec_rank integer not null default 0,
  inclusion_percent numeric(6, 2),
  card_deck_count integer,
  commander_deck_count integer,
  fetch_status text not null default 'ok' check (fetch_status in ('ok', 'no_match', 'error')),
  fetch_error text,
  source_url text,
  scraped_at timestamptz not null default timezone('utc', now()),
  created_at timestamptz not null default timezone('utc', now())
);

create unique index if not exists edhrec_card_commander_recs_card_rank_idx
  on public.edhrec_card_commander_recs (card_key_type, card_key, edhrec_rank);

create index if not exists edhrec_card_commander_recs_lookup_idx
  on public.edhrec_card_commander_recs (card_key_type, card_key, scraped_at desc);

create index if not exists edhrec_card_commander_recs_name_idx
  on public.edhrec_card_commander_recs (normalized_card_name, normalized_commander_name);

alter table public.edhrec_card_commander_recs enable row level security;

create table if not exists public.deck_card_commander_matches (
  id bigint generated by default as identity primary key,
  deck_card_id bigint not null references public.deck_cards (id) on delete cascade,
  deck_id bigint not null references public.decks (id) on delete cascade,
  user_id uuid not null references auth.users (id) on delete cascade,
  card_name text not null,
  card_quantity integer not null default 1,
  cache_card_key_type text not null check (cache_card_key_type in ('oracle_id', 'name')),
  cache_card_key text not null,
  match_status text not null default 'matched' check (match_status in ('matched', 'no_match', 'error')),
  matched_commander_name text,
  normalized_commander_name text,
  edhrec_rank integer,
  inclusion_percent numeric(6, 2),
  card_deck_count integer,
  commander_deck_count integer,
  source_url text,
  cache_scraped_at timestamptz,
  matched_at timestamptz not null default timezone('utc', now()),
  created_at timestamptz not null default timezone('utc', now())
);

create unique index if not exists deck_card_commander_matches_deck_card_idx
  on public.deck_card_commander_matches (deck_card_id);

create index if not exists deck_card_commander_matches_user_idx
  on public.deck_card_commander_matches (user_id, matched_at desc);

create index if not exists deck_card_commander_matches_deck_idx
  on public.deck_card_commander_matches (deck_id, match_status, edhrec_rank);

create index if not exists deck_card_commander_matches_commander_idx
  on public.deck_card_commander_matches (user_id, normalized_commander_name, match_status);

alter table public.deck_card_commander_matches enable row level security;

drop policy if exists "deck card commander matches select own" on public.deck_card_commander_matches;
create policy "deck card commander matches select own"
  on public.deck_card_commander_matches
  for select
  to authenticated
  using (auth.uid() = user_id);
