-- QShip: AI-curated monthly singles subscription (docs/ai-trader-spec.md).
-- Subscriptions and preferences, per-printing price history, market signals,
-- hub inventory (house pool + QShip Supply inbound), boxes and their items,
-- cached card stories, sell signals, shipments, and an audit log.
-- Idempotent: create-if-not-exists / add-column-if-not-exists / drop-policy-
-- if-exists guards make it safe to re-run.

create table if not exists public.qship_subscriptions (
  user_id uuid primary key references auth.users(id) on delete cascade,
  plan_key text not null default 'standard',
  status text not null default 'active',
  billing_interval text not null default 'monthly',
  box_value_usd numeric not null,
  fee_rate numeric not null,
  currency text not null default 'USD',
  stripe_customer_id text,
  stripe_payment_method_id text,
  fulfillment_mode text not null default 'vault_quarterly',
  shipping_level text not null default 'tracked_padded_mailer',
  risk_profile text not null default 'balanced',
  auto_approve boolean not null default true,
  auto_approve_consented_at timestamptz,
  review_window_hours integer not null default 72,
  cycle_anchor_day integer not null default 1,
  box_credit_usd numeric not null default 0,
  prepaid_boxes_remaining integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (plan_key in ('starter', 'standard', 'collector')),
  check (status in ('active', 'paused', 'past_due', 'cancelled')),
  check (billing_interval in ('monthly', 'annual')),
  check (fulfillment_mode in ('vault_quarterly', 'ship_monthly')),
  check (shipping_level in ('pwe_untracked', 'tracked_padded_mailer', 'tracked_insured')),
  check (risk_profile in ('player', 'balanced', 'speculator')),
  check (fee_rate >= 0 and fee_rate <= 0.07),
  check (review_window_hours between 24 and 168),
  check (cycle_anchor_day between 1 and 28),
  check (box_credit_usd >= 0),
  check (prepaid_boxes_remaining >= 0)
);

create table if not exists public.qship_preferences (
  user_id uuid primary key references auth.users(id) on delete cascade,
  focus_deck_ids bigint[] not null default '{}'::bigint[],
  finish_pref text not null default 'any',
  frame_prefs text[] not null default '{}'::text[],
  favorite_artists text[] not null default '{}'::text[],
  lore_interests text[] not null default '{}'::text[],
  blocked_oracle_ids text[] not null default '{}'::text[],
  blocked_set_codes text[] not null default '{}'::text[],
  blocked_artists text[] not null default '{}'::text[],
  min_condition text not null default 'light_play',
  language text not null default 'en',
  goals text,
  goal_tags text[] not null default '{}'::text[],
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (finish_pref in ('nonfoil', 'foil', 'etched', 'any')),
  check (min_condition in ('damaged', 'heavy_play', 'moderate_play', 'light_play', 'near_mint'))
);

-- Daily price per printing. Written by the price cron with the service role.
create table if not exists public.card_price_snapshots (
  scryfall_id text not null,
  captured_on date not null,
  usd numeric,
  usd_foil numeric,
  usd_etched numeric,
  eur numeric,
  buylist_usd numeric,
  buylist_source text,
  source text not null default 'scryfall',
  created_at timestamptz not null default now(),
  primary key (scryfall_id, captured_on)
);

create index if not exists card_price_snapshots_captured_idx
  on public.card_price_snapshots (captured_on desc);

create table if not exists public.market_signals (
  id bigint generated by default as identity primary key,
  scryfall_id text,
  oracle_id text,
  kind text not null,
  strength numeric not null default 0,
  detail text not null,
  source_url text,
  detected_at timestamptz not null default now(),
  expires_at timestamptz,
  check (kind in ('momentum', 'reprint_risk', 'new_synergy', 'meta_rise', 'rotation', 'spike')),
  check (scryfall_id is not null or oracle_id is not null)
);

create index if not exists market_signals_oracle_idx
  on public.market_signals (oracle_id, kind);

create index if not exists market_signals_scryfall_idx
  on public.market_signals (scryfall_id, kind);

-- Everything that is, or will be, at the hub: house pool stock plus QShip
-- Supply copies on their way in. owner_user_id is set once a box allocates it.
create table if not exists public.qship_inventory (
  id bigint generated by default as identity primary key,
  scryfall_id text not null,
  oracle_id text not null,
  card_name text not null,
  set_code text,
  set_name text,
  collector_number text,
  image_url text,
  condition text not null default 'near_mint',
  foil boolean not null default false,
  finish text not null default 'nonfoil',
  language text not null default 'en',
  acquisition_cost_usd numeric not null,
  acquisition_channel text not null,
  source_single_inventory_item_id bigint references public.single_inventory_items(id) on delete set null,
  source_singles_order_id bigint references public.singles_orders(id) on delete set null,
  status text not null default 'receiving',
  owner_user_id uuid references auth.users(id) on delete set null,
  reserved_for_box_id bigint,
  bin_location text,
  intake_photo_url text,
  expected_by date,
  received_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (condition in ('damaged', 'heavy_play', 'moderate_play', 'light_play', 'near_mint')),
  check (finish in ('nonfoil', 'foil', 'etched')),
  check (acquisition_channel in ('trade_in', 'arber_ebay', 'trade_network', 'supply', 'wholesale')),
  check (status in (
    'inbound', 'receiving', 'available', 'reserved', 'vaulted',
    'ship_requested', 'shipped', 'traded_in', 'sold', 'failed'
  )),
  check (acquisition_cost_usd >= 0)
);

create index if not exists qship_inventory_status_idx
  on public.qship_inventory (status, oracle_id);

create index if not exists qship_inventory_owner_idx
  on public.qship_inventory (owner_user_id, status);

alter table public.single_inventory_items
  add column if not exists qship_supply_opt_in boolean not null default false,
  add column if not exists qship_supply_price_usd numeric;

create index if not exists single_inventory_items_qship_supply_idx
  on public.single_inventory_items (qship_supply_opt_in, marketplace_status)
  where qship_supply_opt_in = true;

create table if not exists public.qship_boxes (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  cycle_month date not null,
  status text not null default 'drafting',
  plan_key text not null,
  box_value_usd numeric not null,
  market_value_at_pick_usd numeric,
  cost_basis_usd numeric,
  fee_usd numeric,
  shipping_level text,
  shipping_usd numeric not null default 0,
  credit_applied_usd numeric not null default 0,
  charged_usd numeric,
  theme_title text,
  theme_story text,
  bundles_considered jsonb not null default '[]'::jsonb,
  model text,
  prompt_version text,
  review_deadline timestamptz,
  approved_at timestamptz,
  auto_approved boolean not null default false,
  stripe_payment_intent_id text,
  shipment_id bigint,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, cycle_month),
  check (status in (
    'drafting', 'preview', 'approved', 'skipped', 'charged',
    'vaulted', 'shipped', 'delivered', 'cancelled'
  )),
  check (plan_key in ('starter', 'standard', 'collector')),
  check (shipping_level is null or shipping_level in ('pwe_untracked', 'tracked_padded_mailer', 'tracked_insured'))
);

create index if not exists qship_boxes_status_idx
  on public.qship_boxes (status, review_deadline);

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'qship_inventory_reserved_for_box_fk'
  ) then
    alter table public.qship_inventory
      add constraint qship_inventory_reserved_for_box_fk
      foreign key (reserved_for_box_id) references public.qship_boxes(id) on delete set null;
  end if;
end $$;

create table if not exists public.qship_box_items (
  id bigint generated by default as identity primary key,
  box_id bigint not null references public.qship_boxes(id) on delete cascade,
  inventory_id bigint not null references public.qship_inventory(id) on delete restrict,
  slot text not null,
  market_price_at_pick_usd numeric not null,
  cost_basis_usd numeric not null,
  score_breakdown jsonb not null default '{}'::jsonb,
  why_for_you text,
  story_id bigint,
  swapped_from_inventory_id bigint references public.qship_inventory(id) on delete set null,
  target_deck_id bigint references public.decks(id) on delete set null,
  created_at timestamptz not null default now(),
  check (slot in ('play', 'hold', 'spec'))
);

create index if not exists qship_box_items_box_idx
  on public.qship_box_items (box_id);

-- One story per printing and prompt version, shared by every member.
create table if not exists public.card_stories (
  id bigint generated by default as identity primary key,
  scryfall_id text not null,
  oracle_id text,
  card_name text not null,
  hook text,
  at_the_table text,
  the_brush text,
  the_lore text,
  fact_pack jsonb not null default '{}'::jsonb,
  citations jsonb not null default '[]'::jsonb,
  model text,
  prompt_version text not null,
  status text not null default 'draft',
  reviewed_by uuid references auth.users(id) on delete set null,
  generated_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (scryfall_id, prompt_version),
  check (status in ('draft', 'review', 'published', 'rejected'))
);

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'qship_box_items_story_fk'
  ) then
    alter table public.qship_box_items
      add constraint qship_box_items_story_fk
      foreign key (story_id) references public.card_stories(id) on delete set null;
  end if;
end $$;

create table if not exists public.qship_sell_signals (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  source_kind text not null,
  source_id text not null,
  card_name text not null,
  oracle_id text,
  kind text not null,
  headline text not null,
  detail text,
  market_price_usd numeric,
  trade_in_cash_usd numeric,
  trade_in_credit_usd numeric,
  suggested_action text not null,
  status text not null default 'open',
  detected_at timestamptz not null default now(),
  expires_at timestamptz,
  updated_at timestamptz not null default now(),
  check (source_kind in ('single_inventory', 'deck_card', 'vault')),
  check (kind in ('reprint_incoming', 'peak', 'buylist_spike', 'dead_weight', 'better_printing')),
  check (suggested_action in ('sell_before_release', 'list_or_trade_in', 'trade_in', 'trade_up')),
  check (status in ('open', 'dismissed', 'listed', 'traded_in', 'expired'))
);

create index if not exists qship_sell_signals_user_idx
  on public.qship_sell_signals (user_id, status, detected_at desc);

create table if not exists public.qship_shipments (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  kind text not null,
  method text not null,
  tracking_code text,
  item_count integer not null default 0,
  declared_value_usd numeric not null default 0,
  insurance_usd numeric not null default 0,
  charged_usd numeric not null default 0,
  shipped_at timestamptz,
  delivered_at timestamptz,
  created_at timestamptz not null default now(),
  check (kind in ('quarterly', 'monthly', 'ship_now')),
  check (method in ('pwe_untracked', 'tracked_padded_mailer', 'tracked_insured'))
);

create table if not exists public.qship_events (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  box_id bigint references public.qship_boxes(id) on delete set null,
  event_type text not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists qship_events_user_idx
  on public.qship_events (user_id, created_at desc);

alter table public.qship_subscriptions enable row level security;
alter table public.qship_preferences enable row level security;
alter table public.card_price_snapshots enable row level security;
alter table public.market_signals enable row level security;
alter table public.qship_inventory enable row level security;
alter table public.qship_boxes enable row level security;
alter table public.qship_box_items enable row level security;
alter table public.card_stories enable row level security;
alter table public.qship_sell_signals enable row level security;
alter table public.qship_shipments enable row level security;
alter table public.qship_events enable row level security;

-- card_price_snapshots and market_signals have no user policies: the crons and
-- the server read and write them with the service role.

drop policy if exists "members read own qship subscription" on public.qship_subscriptions;
create policy "members read own qship subscription"
  on public.qship_subscriptions
  for select
  using (auth.uid() = user_id or auth.jwt() ->> 'email' = 'tim.felsky@gmail.com');

drop policy if exists "members manage own qship preferences" on public.qship_preferences;
create policy "members manage own qship preferences"
  on public.qship_preferences
  for all
  using (auth.uid() = user_id or auth.jwt() ->> 'email' = 'tim.felsky@gmail.com')
  with check (auth.uid() = user_id or auth.jwt() ->> 'email' = 'tim.felsky@gmail.com');

drop policy if exists "members read own vault inventory" on public.qship_inventory;
create policy "members read own vault inventory"
  on public.qship_inventory
  for select
  using (auth.uid() = owner_user_id or auth.jwt() ->> 'email' = 'tim.felsky@gmail.com');

drop policy if exists "members read own qship boxes" on public.qship_boxes;
create policy "members read own qship boxes"
  on public.qship_boxes
  for select
  using (auth.uid() = user_id or auth.jwt() ->> 'email' = 'tim.felsky@gmail.com');

drop policy if exists "members read own qship box items" on public.qship_box_items;
create policy "members read own qship box items"
  on public.qship_box_items
  for select
  using (
    exists (
      select 1 from public.qship_boxes box
      where box.id = qship_box_items.box_id
        and (box.user_id = auth.uid() or auth.jwt() ->> 'email' = 'tim.felsky@gmail.com')
    )
  );

drop policy if exists "public read published card stories" on public.card_stories;
create policy "public read published card stories"
  on public.card_stories
  for select
  using (status = 'published' or auth.jwt() ->> 'email' = 'tim.felsky@gmail.com');

drop policy if exists "members read own sell signals" on public.qship_sell_signals;
create policy "members read own sell signals"
  on public.qship_sell_signals
  for select
  using (auth.uid() = user_id or auth.jwt() ->> 'email' = 'tim.felsky@gmail.com');

drop policy if exists "members read own qship shipments" on public.qship_shipments;
create policy "members read own qship shipments"
  on public.qship_shipments
  for select
  using (auth.uid() = user_id or auth.jwt() ->> 'email' = 'tim.felsky@gmail.com');

drop policy if exists "members read own qship events" on public.qship_events;
create policy "members read own qship events"
  on public.qship_events
  for select
  using (auth.uid() = user_id or auth.jwt() ->> 'email' = 'tim.felsky@gmail.com');
